#!/usr/bin/env python3
"""
WhatsApp Delivery - Auto-start Bailey + Send to #my-notes
Uses existing WhatsAppWebClient (KISS + DRY)
"""

import asyncio
import sys
from pathlib import Path

# Add Jotty to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from Jotty.apps.cli.channels.whatsapp_web.client import WhatsAppWebClient


async def find_mynotes_chat(client: WhatsAppWebClient):
    """Find #my-notes chat from chats list."""
    chats = await client.get_chats(limit=100)

    for chat in chats:
        name = chat.get("name", "").lower()
        if "my-notes" in name or "mynotes" in name:
            return chat.get("id")

    return None


async def main():
    pdf_path = "/home/coder/jotty/outputs/multiagent_systems_olympiad.pdf"

    if not Path(pdf_path).exists():
        print(f"❌ PDF not found: {pdf_path}")
        print("   Run multiagent_comprehensive_working.py first")
        sys.exit(1)

    print("=" * 80)
    print("WhatsApp Delivery - #my-notes")
    print("=" * 80 + "\n")

    print("🚀 Starting WhatsApp Web client...")
    print("   • Auto-installs dependencies if needed")
    print("   • Loads saved session if available")
    print("   • Shows QR code if first time\n")

    # Use existing WhatsAppWebClient
    client = WhatsAppWebClient()

    started = await client.start()
    if not started:
        print("❌ Failed to start WhatsApp client")
        sys.exit(1)

    # Wait for connection
    print("⏳ Waiting for WhatsApp connection...")
    for i in range(60):
        await asyncio.sleep(1)
        if client.connected:
            print("✅ Connected to WhatsApp!\n")
            break
        if client.qr_code and i == 5:
            print("\n📱 Scan QR code with WhatsApp app (shown above)\n")
    else:
        print("❌ Connection timeout")
        await client.stop()
        sys.exit(1)

    # Find #my-notes chat
    print("🔍 Finding #my-notes chat...")
    mynotes_id = await find_mynotes_chat(client)

    if not mynotes_id:
        print("❌ #my-notes chat not found")
        print("   Available chats:")
        chats = await client.get_chats(limit=20)
        for chat in chats[:10]:
            print(f"   - {chat.get('name')}")
        await client.stop()
        sys.exit(1)

    print(f"✅ Found #my-notes: {mynotes_id}\n")

    # Send PDF
    print("📤 Sending PDF to #my-notes...")
    print(f"   File: {Path(pdf_path).stat().st_size / 1024:.1f} KB\n")

    result = await client.send_media(
        to=mynotes_id,
        file_path=pdf_path,
        caption="""📚 *Multi-Agent Systems Course*

*Comprehensive Technical Deep Dive (Olympiad Quality)*

Generated by Jotty Olympiad Learning Swarm
26,717 words | 53 pages""",
    )

    if result.get("success"):
        print(f"✅ Delivered to #my-notes!")
        print(f"   Message ID: {result.get('message_id')}\n")
    else:
        print(f"❌ Failed: {result.get('error')}\n")

    # Cleanup
    await client.stop()

    print("=" * 80)
    print("COMPLETE!")
    print("=" * 80)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n⚠️  Interrupted by user")
        sys.exit(0)
