#!/usr/bin/env python3
"""
COMPREHENSIVE MULTI-AGENT SYSTEMS COURSE
Using the ACTUAL WORKING olympiad_learning_swarm.learn_topic()
Delivers to Telegram + WhatsApp from environment
"""

import asyncio
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment
env_path = Path(__file__).parent.parent.parent / "Jotty" / ".env.anthropic"
if env_path.exists():
    load_dotenv(env_path)


async def main():
    from Jotty.core.swarms.olympiad_learning_swarm import learn_topic
    from Jotty.core.workflows import OutputChannelManager

    print("\n" + "="*80)
    print("COMPREHENSIVE MULTI-AGENT SYSTEMS COURSE")
    print("Using Proven Olympiad Learning Swarm")
    print("="*80 + "\n")

    print("🚀 Generating comprehensive course...")
    print("   Using olympiad_learning_swarm.learn_topic()")
    print("   This will take 5-8 minutes and generate 10,000+ words")
    print()

    # Use the ACTUAL working learn_topic function
    result = await learn_topic(
        subject="general",  # Computer Science concepts
        topic="Multi-Agent Systems: Architectures, Coordination, Memory, and Learning",
        student_name="Advanced Researcher",
        depth="deep",  # Deep dive
        target="advanced",  # Advanced/research level
        send_telegram=False  # We'll handle delivery manually
    )

    print()
    print("✅ Course Generation Complete!")
    print(f"   Result type: {type(result)}")

    # Extract content
    if hasattr(result, 'content'):
        content = result.content
    elif hasattr(result, 'lesson_content'):
        content = result.lesson_content
    elif hasattr(result, '__dict__'):
        print(f"   Available attributes: {list(result.__dict__.keys())}")
        # Try to find any content field
        for key in result.__dict__.keys():
            if 'content' in key.lower() or 'output' in key.lower() or 'text' in key.lower():
                content = getattr(result, key)
                break
        else:
            content = str(result)
    else:
        content = str(result)

    # Save markdown
    output_dir = Path.home() / "jotty" / "outputs"
    output_dir.mkdir(parents=True, exist_ok=True)

    markdown_path = output_dir / "multiagent_systems_olympiad.md"
    with open(markdown_path, 'w', encoding='utf-8') as f:
        f.write(content)

    content_size = len(content)
    word_count = content_size // 5
    page_count = word_count // 500

    print(f"\n✅ Saved course: {markdown_path}")
    print(f"   Size: {content_size:,} characters ({content_size/1024:.1f}KB)")
    print(f"   Words: ~{word_count:,}")
    print(f"   Pages: ~{page_count}")
    print()

    # Generate PDF
    print("📄 Generating PDF...")
    from Jotty.core.workflows import OutputFormatManager

    format_manager = OutputFormatManager(output_dir=str(output_dir))
    pdf_result = format_manager.generate_pdf(
        markdown_path=str(markdown_path),
        title="Multi-Agent Systems: Comprehensive Technical Course",
        author="Jotty AI Olympiad Learning System",
        page_size="a4"
    )

    if pdf_result.success:
        file_to_send = pdf_result.file_path
        file_format = "PDF"
        pdf_size_kb = Path(pdf_result.file_path).stat().st_size / 1024
        print(f"✅ PDF: {Path(pdf_result.file_path).name} ({pdf_size_kb:.1f} KB)")
    else:
        print(f"❌ PDF failed: {pdf_result.error}")
        file_to_send = str(markdown_path)
        file_format = "Markdown"

    print()

    # Send to Telegram
    print("📤 Sending to Telegram...")
    channel_manager = OutputChannelManager()

    telegram_result = await channel_manager.send_to_telegram(
        file_path=file_to_send,
        caption=f"""📚 <b>Multi-Agent Systems Course</b>

<b>Comprehensive Technical Deep Dive</b>

📊 ~{word_count:,} words (~{page_count} pages)

Generated by Jotty Olympiad Learning System""",
        parse_mode="HTML"
    )

    if telegram_result.success:
        print(f"✅ Telegram: Message ID {telegram_result.message_id}")
    else:
        print(f"❌ Telegram failed: {telegram_result.error}")

    # Send to WhatsApp
    whatsapp_to = os.environ.get('WHATSAPP_CHANNEL') or os.environ.get('WHATSAPP_TO')

    if whatsapp_to:
        print(f"\n📤 Sending to WhatsApp: {whatsapp_to}")

        whatsapp_result = await channel_manager.send_to_whatsapp(
            to=whatsapp_to,
            file_path=file_to_send,
            caption=f"""📚 *Multi-Agent Systems Course*

*Comprehensive Technical Deep Dive*

📊 ~{word_count:,} words ({page_count} pages)

Generated by Jotty AI""",
            provider="baileys"
        )

        if whatsapp_result.success:
            print(f"✅ WhatsApp: Message ID {whatsapp_result.message_id}")
        else:
            print(f"❌ WhatsApp failed: {whatsapp_result.error}")
    else:
        print("\n⚠️  WhatsApp not configured")
        print("   Set in .env.anthropic: WHATSAPP_CHANNEL='your-jid@g.us'")

    print("\n" + "="*80)
    print("COMPLETE!")
    print("="*80 + "\n")


if __name__ == '__main__':
    asyncio.run(main())
