#!/usr/bin/env python3
"""
COMPREHENSIVE MULTI-AGENT SYSTEMS COURSE
Using the ACTUAL WORKING olympiad_learning_swarm.learn_topic()
Delivers to Telegram + WhatsApp from environment
"""

import asyncio
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment
env_path = Path(__file__).parent.parent.parent / "Jotty" / ".env.anthropic"
if env_path.exists():
    load_dotenv(env_path)


async def main():
    from Jotty.core.intelligence.swarms.olympiad_learning_swarm import learn_topic
    from Jotty.core.modes.workflow import OutputChannelManager

    print("\n" + "="*80)
    print("COMPREHENSIVE MULTI-AGENT SYSTEMS COURSE")
    print("Using Proven Olympiad Learning Swarm")
    print("="*80 + "\n")

    print("🚀 Generating comprehensive course...")
    print("   Using olympiad_learning_swarm.learn_topic()")
    print("   This will take 5-8 minutes and generate 10,000+ words")
    print()

    # Use the ACTUAL working learn_topic function
    result = await learn_topic(
        subject="general",  # Computer Science concepts
        topic="Multi-Agent Systems: Architectures, Coordination, Memory, and Learning",
        student_name="Advanced Researcher",
        depth="deep",  # Deep dive
        target="advanced",  # Advanced/research level
        send_telegram=False  # We'll handle delivery manually
    )

    print()
    print("✅ Course Generation Complete!")
    print(f"   Cost: ${result.cost:.6f}" if hasattr(result, 'cost') else "")
    print(f"   Result attributes: {list(result.__dict__.keys())}")

    # Check if PDF was already generated by olympiad swarm
    if hasattr(result, 'pdf_path') and result.pdf_path and Path(result.pdf_path).exists():
        file_to_send = result.pdf_path
        file_format = "PDF (Olympiad-generated)"
        pdf_size_kb = Path(result.pdf_path).stat().st_size / 1024

        print(f"\n✅ Using Olympiad-generated PDF:")
        print(f"   Path: {result.pdf_path}")
        print(f"   Size: {pdf_size_kb:.1f} KB")
    else:
        print("\n⚠️  No PDF generated by olympiad swarm")
        file_to_send = None
        file_format = "None"

    print()

    if not file_to_send:
        print("❌ No file to send - check olympiad swarm configuration")
        return

    # Send to Telegram
    print("📤 Sending to Telegram...")
    channel_manager = OutputChannelManager()

    telegram_result = await channel_manager.send_to_telegram(
        file_path=file_to_send,
        caption=f"""📚 <b>Multi-Agent Systems Course</b>

<b>Comprehensive Technical Deep Dive (Olympiad Quality)</b>

Generated by Jotty Olympiad Learning Swarm""",
        parse_mode="HTML"
    )

    if telegram_result.success:
        print(f"✅ Telegram: Message ID {telegram_result.message_id}")
    else:
        print(f"❌ Telegram failed: {telegram_result.error}")

    # Send to WhatsApp
    whatsapp_to = os.environ.get('WHATSAPP_CHANNEL') or os.environ.get('WHATSAPP_TO')

    if whatsapp_to:
        print(f"\n📤 Sending to WhatsApp: {whatsapp_to}")

        whatsapp_result = await channel_manager.send_to_whatsapp(
            to=whatsapp_to,
            file_path=file_to_send,
            caption=f"""📚 *Multi-Agent Systems Course*

*Comprehensive Technical Deep Dive*

Generated by Jotty Olympiad Learning Swarm""",
            provider="baileys"
        )

        if whatsapp_result.success:
            print(f"✅ WhatsApp: Message ID {whatsapp_result.message_id}")
        else:
            print(f"❌ WhatsApp failed: {whatsapp_result.error}")
    else:
        print("\n⚠️  WhatsApp not configured")
        print("   Set in .env.anthropic: WHATSAPP_CHANNEL='your-jid@g.us'")

    print("\n" + "="*80)
    print("COMPLETE!")
    print("="*80 + "\n")


if __name__ == '__main__':
    asyncio.run(main())
