#!/usr/bin/env python3
"""
COMPREHENSIVE MULTI-AGENT SYSTEMS COURSE + WhatsApp Delivery
Auto-starts WhatsApp Web client, loads session, sends to #my-notes
Uses existing WhatsAppWebClient (KISS + DRY)
"""

import asyncio
import sys
from pathlib import Path
from dotenv import load_dotenv

# Add Jotty to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

# Load environment
env_path = Path(__file__).parent.parent.parent / ".env.anthropic"
if env_path.exists():
    load_dotenv(env_path)

from cli.channels.whatsapp_web.client import WhatsAppWebClient


async def find_mynotes_chat(client: WhatsAppWebClient):
    """Find #my-notes chat from chats list."""
    chats = await client.get_chats(limit=100)
    for chat in chats:
        name = chat.get('name', '').lower()
        if 'my-notes' in name or 'mynotes' in name:
            return chat.get('id')
    return None


async def main():
    from Jotty.core.swarms.olympiad_learning_swarm import learn_topic
    from Jotty.core.workflows import OutputChannelManager

    print("\n" + "="*80)
    print("COMPREHENSIVE MULTI-AGENT SYSTEMS COURSE")
    print("Using Olympiad Learning Swarm + WhatsApp #my-notes Delivery")
    print("="*80 + "\n")

    # Check if we should regenerate or use existing
    pdf_path = Path("/home/coder/jotty/outputs/multiagent_systems_olympiad.pdf")

    if pdf_path.exists():
        print(f"✅ Using existing PDF: {pdf_path}")
        print(f"   Size: {pdf_path.stat().st_size / 1024:.1f} KB\n")
        file_to_send = str(pdf_path)
    else:
        print("🚀 Generating comprehensive course...")
        print("   Using olympiad_learning_swarm.learn_topic()")
        print("   This will take 5-8 minutes and generate 10,000+ words\n")

        result = await learn_topic(
            subject="general",
            topic="Multi-Agent Systems: Architectures, Coordination, Memory, and Learning",
            student_name="Advanced Researcher",
            depth="deep",
            target="advanced",
            send_telegram=False
        )

        print("\n✅ Course Generation Complete!")
        if hasattr(result, 'cost'):
            print(f"   Cost: ${result.cost:.6f}")

        if hasattr(result, 'pdf_path') and result.pdf_path and Path(result.pdf_path).exists():
            file_to_send = result.pdf_path
            print(f"\n✅ Using Olympiad-generated PDF: {result.pdf_path}")
        else:
            print("\n❌ No PDF generated")
            return

    # Send to Telegram
    print("📤 Sending to Telegram...")
    channel_manager = OutputChannelManager()

    telegram_result = await channel_manager.send_to_telegram(
        file_path=file_to_send,
        caption="""📚 <b>Multi-Agent Systems Course</b>

<b>Comprehensive Technical Deep Dive (Olympiad Quality)</b>

Generated by Jotty Olympiad Learning Swarm""",
        parse_mode="HTML"
    )

    if telegram_result.success:
        print(f"✅ Telegram: Message ID {telegram_result.message_id}\n")
    else:
        print(f"❌ Telegram failed: {telegram_result.error}\n")

    # Send to WhatsApp #my-notes
    print("📤 Sending to WhatsApp #my-notes...")
    print("   • Auto-starts WhatsApp Web client")
    print("   • Loads saved session")
    print("   • Shows QR code if first time\n")

    client = WhatsAppWebClient()

    started = await client.start()
    if not started:
        print("❌ WhatsApp client failed to start")
        print("   Continuing without WhatsApp delivery\n")
    else:
        # Wait for connection
        print("⏳ Connecting to WhatsApp...")
        for i in range(60):
            await asyncio.sleep(1)
            if client.connected:
                print("✅ Connected!\n")
                break
            if client.qr_code and i == 5:
                print("\n📱 Scan QR code with WhatsApp (shown above)\n")
        else:
            print("❌ Connection timeout\n")
            await client.stop()
            client = None

        if client and client.connected:
            # Find #my-notes
            print("🔍 Finding #my-notes chat...")
            mynotes_id = await find_mynotes_chat(client)

            if mynotes_id:
                print(f"✅ Found: {mynotes_id}\n")

                # Send PDF
                print("📤 Sending PDF...")
                result = await client.send_media(
                    to=mynotes_id,
                    file_path=file_to_send,
                    caption="""📚 *Multi-Agent Systems Course*

*Comprehensive Technical Deep Dive (Olympiad Quality)*

Generated by Jotty Olympiad Learning Swarm
26,717 words | 53 pages"""
                )

                if result.get('success'):
                    print(f"✅ WhatsApp: Message ID {result.get('message_id')}\n")
                else:
                    print(f"❌ WhatsApp failed: {result.get('error')}\n")
            else:
                print("❌ #my-notes chat not found\n")

            await client.stop()

    print("="*80)
    print("COMPLETE!")
    print("="*80 + "\n")


if __name__ == '__main__':
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\n⚠️  Interrupted by user")
        sys.exit(0)
