#!/usr/bin/env python3
"""
Test Telegram and WhatsApp delivery with markdown file
"""

import os
from pathlib import Path


def main():
    from Jotty.core.intelligence.orchestration.pipelines import OutputChannelManager

    print("\n" + "=" * 80)
    print("CHANNEL DELIVERY TEST: Telegram & WhatsApp")
    print("=" * 80 + "\n")

    # Check if markdown exists
    markdown_path = Path.home() / "jotty" / "outputs" / "meditation_research.md"

    if not markdown_path.exists():
        print(f"❌ Markdown file not found: {markdown_path}")
        return

    print(f"📄 Found markdown: {markdown_path}")
    file_size = markdown_path.stat().st_size
    print(f"   Size: {file_size:,} bytes\n")

    # Read first 500 chars as preview
    with open(markdown_path, "r", encoding="utf-8") as f:
        preview = f.read(500)

    print("📄 Content preview:")
    print("-" * 80)
    print(preview[:300] + "...\n")

    channel_manager = OutputChannelManager()

    # ═══════════════════════════════════════════════════════════════════════
    # Test 1: Send message to Telegram
    # ═══════════════════════════════════════════════════════════════════════

    print("TEST 1: Send Message to Telegram")
    print("-" * 80 + "\n")

    telegram_result = channel_manager.send_to_telegram(
        message=(
            "📚 <b>Research Report Test</b>\n\n"
            "Topic: Benefits of Daily Meditation for Mental Health\n\n"
            "This is a test message from Jotty's new multi-channel output system!\n\n"
            "✅ Research workflow complete\n"
            "✅ Markdown generated\n"
            "✅ Channel delivery working\n\n"
            "Next: Will send actual file..."
        ),
        parse_mode="HTML",
    )

    if telegram_result.success:
        print(f"✅ Message sent to Telegram!")
        print(f"   Message ID: {telegram_result.message_id}\n")
    else:
        print(f"❌ Telegram failed: {telegram_result.error}\n")

    # ═══════════════════════════════════════════════════════════════════════
    # Test 2: Send markdown file to Telegram
    # ═══════════════════════════════════════════════════════════════════════

    print("TEST 2: Send Markdown File to Telegram")
    print("-" * 80 + "\n")

    telegram_file_result = channel_manager.send_to_telegram(
        file_path=str(markdown_path),
        caption=(
            "📚 <b>Meditation Research Report</b>\n\n"
            "✅ Generated by Jotty Research Workflow\n"
            f"📄 Size: {file_size:,} bytes\n"
            "🔗 Markdown format\n\n"
            "View on Telegram!"
        ),
        parse_mode="HTML",
    )

    if telegram_file_result.success:
        print(f"✅ File sent to Telegram!")
        print(f"   Message ID: {telegram_file_result.message_id}\n")
    else:
        print(f"❌ Telegram file send failed: {telegram_file_result.error}\n")

    # ═══════════════════════════════════════════════════════════════════════
    # Test 3: Send to WhatsApp (if configured)
    # ═══════════════════════════════════════════════════════════════════════

    print("TEST 3: Send to WhatsApp")
    print("-" * 80 + "\n")

    whatsapp_to = os.environ.get("WHATSAPP_TO")

    if whatsapp_to:
        print(f"📤 Sending to WhatsApp: {whatsapp_to}")

        # Send message first
        whatsapp_msg_result = channel_manager.send_to_whatsapp(
            to=whatsapp_to,
            message=(
                "📚 *Research Report Test*\n\n"
                "Topic: Benefits of Daily Meditation\n\n"
                "This is a test from Jotty's multi-channel system!\n\n"
                "✅ Research complete\n"
                "✅ File will follow..."
            ),
            provider="auto",
        )

        if whatsapp_msg_result.success:
            print(f"✅ Message sent to WhatsApp!")
            print(f"   Message ID: {whatsapp_msg_result.message_id}")
            print(f"   Provider: {whatsapp_msg_result.metadata.get('provider')}\n")
        else:
            print(f"❌ WhatsApp message failed: {whatsapp_msg_result.error}\n")

        # Send file
        print(f"📤 Sending file to WhatsApp...")
        whatsapp_file_result = channel_manager.send_to_whatsapp(
            to=whatsapp_to,
            file_path=str(markdown_path),
            caption="📚 Meditation Research (Markdown)",
            provider="auto",
        )

        if whatsapp_file_result.success:
            print(f"✅ File sent to WhatsApp!")
            print(f"   Message ID: {whatsapp_file_result.message_id}\n")
        else:
            print(f"❌ WhatsApp file send failed: {whatsapp_file_result.error}\n")
    else:
        print("⚠️  WHATSAPP_TO not configured")
        print("   Set environment variable: WHATSAPP_TO='14155238886' (with country code)\n")

    # ═══════════════════════════════════════════════════════════════════════
    # Test 4: Batch send to both channels
    # ═══════════════════════════════════════════════════════════════════════

    print("TEST 4: Batch Send to All Channels")
    print("-" * 80 + "\n")

    channels = ["telegram"]
    params = {}

    if whatsapp_to:
        channels.append("whatsapp")
        params["whatsapp_to"] = whatsapp_to

    print(f"📤 Sending to {len(channels)} channels: {', '.join(channels)}\n")

    batch_results = channel_manager.send_to_all(
        channels=channels,
        file_path=str(markdown_path),
        caption="📚 Meditation Research - Multi-Channel Test",
        **params,
    )

    batch_summary = channel_manager.get_summary(batch_results)
    print(f"📊 Batch send complete:")
    print(f"   ✅ Successful: {batch_summary['successful']}/{batch_summary['total']}")

    for ch in batch_summary["successful_channels"]:
        result = batch_results[ch]
        print(f"   ✅ {ch.upper()}: Message ID {result.message_id}")

    if batch_summary["failed_channels"]:
        print(f"\n   ❌ Failed:")
        for ch in batch_summary["failed_channels"]:
            error = batch_summary["errors"].get(ch, "Unknown")
            print(f"   {ch.upper()}: {error}")

    print()

    # ═══════════════════════════════════════════════════════════════════════
    # Summary
    # ═══════════════════════════════════════════════════════════════════════

    print("=" * 80)
    print("CHANNEL DELIVERY TEST COMPLETE")
    print("=" * 80 + "\n")

    total_successful = 0
    if telegram_result.success:
        total_successful += 1
    if telegram_file_result.success:
        total_successful += 1
    if whatsapp_to:
        if "whatsapp_msg_result" in locals() and whatsapp_msg_result.success:
            total_successful += 1
        if "whatsapp_file_result" in locals() and whatsapp_file_result.success:
            total_successful += 1

    print(f"✅ Successful deliveries: {total_successful}")
    print()
    print("Channels tested:")
    print(f"   ✅ Telegram (message): {'✓' if telegram_result.success else '✗'}")
    print(f"   ✅ Telegram (file): {'✓' if telegram_file_result.success else '✗'}")
    if whatsapp_to:
        print(
            f"   ✅ WhatsApp (message): {'✓' if 'whatsapp_msg_result' in locals() and whatsapp_msg_result.success else '✗'}"
        )
        print(
            f"   ✅ WhatsApp (file): {'✓' if 'whatsapp_file_result' in locals() and whatsapp_file_result.success else '✗'}"
        )
    print()


if __name__ == "__main__":
    main()
