# Memory: ChromaDB
# =================
# Vector database with semantic search

backend: chroma
implementation: core.memory.chroma_backend.ChromaMemory

settings:
  max_entries: 10000
  persist: true
  persist_directory: ./data/chroma
  collection_name: jotty_memory

embedding:
  model: sentence-transformers/all-MiniLM-L6-v2
  cache: true

search:
  strategy: semantic  # Vector similarity
  top_k: 10
  threshold: 0.7

consolidation:
  enabled: false
