"""
Jotty Swarm Templates
=====================

All swarms are **lazily loaded** — importing ``core.swarms`` does NOT
trigger heavy dependency chains.  A swarm module is only loaded on
first attribute access (e.g. ``from core.swarms import CodingSwarm``).

Available Swarms:
    PilotSwarm (autonomous goal-completion),
    ResearchSwarm, FundamentalSwarm, DataAnalysisSwarm,
    CodingSwarm, TestingSwarm, ReviewSwarm,
    IdeaWriterSwarm, DevOpsSwarm,
    ArxivLearningSwarm, OlympiadLearningSwarm, PerspectiveLearningSwarm, LearningSwarm

Quick usage::

    from core.swarms import CodingSwarm, code
    result = await code("Create a REST API")
"""

import importlib as _importlib
from typing import Any

# =========================================================================
# EAGER: Base infrastructure (lightweight, needed everywhere)
# =========================================================================
from .base import (
    AgentCoordinator,
    AgentSpec,
    CoordinationPattern,
    CoordinationResult,
    MergeStrategy,
    SwarmTemplate,
    TeamCoordinator,
    TeamResult,
)

# =========================================================================
# LAZY: Swarm modules — loaded on first access via __getattr__
# =========================================================================

_LAZY_IMPORTS: dict[str, str] = {
    # --- swarm_signatures (DSPy-dependent, loaded lazily) ---
    "ExpertEvaluationSignature": "._base.swarm_signatures",
    "ReviewerAnalysisSignature": "._base.swarm_signatures",
    "PlannerOptimizationSignature": "._base.swarm_signatures",
    "ActorExecutionSignature": "._base.swarm_signatures",
    "AuditorVerificationSignature": "._base.swarm_signatures",
    "LearnerExtractionSignature": "._base.swarm_signatures",
    # --- research_swarm ---
    "ResearchSwarm": ".research_swarm",
    "ResearchConfig": ".research_swarm",
    "ResearchResult": ".research_swarm",
    "RatingType": ".research_swarm",
    "research": ".research_swarm",
    "research_sync": ".research_swarm",
    "SwarmLearningAgent": ".research_swarm",
    "DataFetcherAgent": ".research_swarm",
    "WebSearchAgent": ".research_swarm",
    "SentimentAgent": ".research_swarm",
    "LLMAnalysisAgent": ".research_swarm",
    "PeerComparisonAgent": ".research_swarm",
    "ChartGeneratorAgent": ".research_swarm",
    "ReportGeneratorAgent": ".research_swarm",
    "TechnicalAnalysisAgent": ".research_swarm",
    "EnhancedChartGeneratorAgent": ".research_swarm",
    "ScreenerAgent": ".research_swarm",
    "SocialSentimentAgent": ".research_swarm",
    "StockAnalysisSignature": ".research_swarm",
    "SentimentAnalysisSignature": ".research_swarm",
    "PeerSelectionSignature": ".research_swarm",
    "SocialSentimentSignature": ".research_swarm",
    "TechnicalSignalsSignature": ".research_swarm",
    # --- coding_swarm ---
    "CodingSwarm": ".coding_swarm",
    "CodingConfig": ".coding_swarm",
    "CodingResult": ".coding_swarm",
    "CodeOutput": ".coding_swarm",
    "CodeLanguage": ".coding_swarm",
    "CodeStyle": ".coding_swarm",
    "code": ".coding_swarm",
    "code_sync": ".coding_swarm",
    "ArchitectAgent": ".coding_swarm",
    "DeveloperAgent": ".coding_swarm",
    "DebuggerAgent": ".coding_swarm",
    "OptimizerAgent": ".coding_swarm",
    "TestWriterAgent": ".coding_swarm",
    "DocWriterAgent": ".coding_swarm",
    # --- testing_swarm ---
    "TestingSwarm": ".templates.testing_swarm",
    "TestingConfig": ".templates.testing_swarm",
    "TestingResult": ".templates.testing_swarm",
    "TestSuite": ".templates.testing_swarm",
    "TestCase": ".templates.testing_swarm",
    "CoverageReport": ".templates.testing_swarm",
    "TestType": ".templates.testing_swarm",
    "TestFramework": ".templates.testing_swarm",
    "CoverageTarget": ".templates.testing_swarm",
    "test": ".templates.testing_swarm",
    "test_sync": ".templates.testing_swarm",
    "CodeAnalyzerAgent": ".templates.testing_swarm",
    "UnitTestAgent": ".templates.testing_swarm",
    "IntegrationTestAgent": ".templates.testing_swarm",
    "E2ETestAgent": ".templates.testing_swarm",
    "CoverageAgent": ".templates.testing_swarm",
    "QualityAgent": ".templates.testing_swarm",
    # --- fundamental_swarm ---
    "FundamentalSwarm": ".templates.fundamental_swarm",
    "FundamentalConfig": ".templates.fundamental_swarm",
    "FundamentalResult": ".templates.fundamental_swarm",
    "FinancialMetrics": ".templates.fundamental_swarm",
    "ValuationMetrics": ".templates.fundamental_swarm",
    "QualityMetrics": ".templates.fundamental_swarm",
    "ValuationResult": ".templates.fundamental_swarm",
    "InvestmentThesis": ".templates.fundamental_swarm",
    "ValuationType": ".templates.fundamental_swarm",
    "InvestmentStyle": ".templates.fundamental_swarm",
    "RatingScale": ".templates.fundamental_swarm",
    "analyze_fundamentals": ".templates.fundamental_swarm",
    "analyze_fundamentals_sync": ".templates.fundamental_swarm",
    "FinancialStatementAgent": ".templates.fundamental_swarm",
    "RatioAnalysisAgent": ".templates.fundamental_swarm",
    "ValuationAgent": ".templates.fundamental_swarm",
    "QualityEarningsAgent": ".templates.fundamental_swarm",
    "ManagementAgent": ".templates.fundamental_swarm",
    "MoatAgent": ".templates.fundamental_swarm",
    "ThesisAgent": ".templates.fundamental_swarm",
    # --- idea_writer_swarm ---
    "IdeaWriterSwarm": ".templates.idea_writer_swarm",
    "WriterConfig": ".templates.idea_writer_swarm",
    "WriterResult": ".templates.idea_writer_swarm",
    "ContentResult": ".templates.idea_writer_swarm",
    "Section": ".templates.idea_writer_swarm",
    "Outline": ".templates.idea_writer_swarm",
    "ContentType": ".templates.idea_writer_swarm",
    "Tone": ".templates.idea_writer_swarm",
    "OutputFormat": ".templates.idea_writer_swarm",
    "write": ".templates.idea_writer_swarm",
    "write_sync": ".templates.idea_writer_swarm",
    "SectionRegistry": ".templates.idea_writer_swarm",
    "SectionWriter": ".templates.idea_writer_swarm",
    "IntroductionWriter": ".templates.idea_writer_swarm",
    "BodySectionWriter": ".templates.idea_writer_swarm",
    "ConclusionWriter": ".templates.idea_writer_swarm",
    "MarketAnalysisWriter": ".templates.idea_writer_swarm",
    "CaseStudiesWriter": ".templates.idea_writer_swarm",
    "TechnicalDeepDiveWriter": ".templates.idea_writer_swarm",
    "ResearchFindingsWriter": ".templates.idea_writer_swarm",
    "OutlineAgent": ".templates.idea_writer_swarm",
    "ResearchAgent": ".templates.idea_writer_swarm",
    "PolishAgent": ".templates.idea_writer_swarm",
    # --- data_analysis_swarm ---
    "DataAnalysisSwarm": ".templates.data_analysis_swarm",
    "DataAnalysisConfig": ".templates.data_analysis_swarm",
    "AnalysisResult": ".templates.data_analysis_swarm",
    "DataProfile": ".templates.data_analysis_swarm",
    "StatisticalResult": ".templates.data_analysis_swarm",
    "Insight": ".templates.data_analysis_swarm",
    "MLRecommendation": ".templates.data_analysis_swarm",
    "Visualization": ".templates.data_analysis_swarm",
    "AnalysisType": ".templates.data_analysis_swarm",
    "DataType": ".templates.data_analysis_swarm",
    "VisualizationType": ".templates.data_analysis_swarm",
    "analyze_data": ".templates.data_analysis_swarm",
    "analyze_data_sync": ".templates.data_analysis_swarm",
    "DataProfilerAgent": ".templates.data_analysis_swarm",
    "EDAAgent": ".templates.data_analysis_swarm",
    "StatisticalAgent": ".templates.data_analysis_swarm",
    "InsightAgent": ".templates.data_analysis_swarm",
    "MLRecommenderAgent": ".templates.data_analysis_swarm",
    "VisualizationAgent": ".templates.data_analysis_swarm",
    # --- devops_swarm ---
    "DevOpsSwarm": ".templates.devops_swarm",
    "DevOpsConfig": ".templates.devops_swarm",
    "DevOpsResult": ".templates.devops_swarm",
    "InfrastructureSpec": ".templates.devops_swarm",
    "PipelineSpec": ".templates.devops_swarm",
    "ContainerSpec": ".templates.devops_swarm",
    "SecurityConfig": ".templates.devops_swarm",
    "MonitoringConfig": ".templates.devops_swarm",
    "CloudProvider": ".templates.devops_swarm",
    "IaCTool": ".templates.devops_swarm",
    "CIProvider": ".templates.devops_swarm",
    "ContainerPlatform": ".templates.devops_swarm",
    "deploy": ".templates.devops_swarm",
    "deploy_sync": ".templates.devops_swarm",
    "InfrastructureArchitect": ".templates.devops_swarm",
    "CICDDesigner": ".templates.devops_swarm",
    "ContainerSpecialist": ".templates.devops_swarm",
    "SecurityHardener": ".templates.devops_swarm",
    "MonitoringSpecialist": ".templates.devops_swarm",
    "IaCGenerator": ".templates.devops_swarm",
    # --- review_swarm ---
    "ReviewSwarm": ".templates.review_swarm",
    "ReviewConfig": ".templates.review_swarm",
    "ReviewResult": ".templates.review_swarm",
    "ReviewComment": ".templates.review_swarm",
    "SecurityFinding": ".templates.review_swarm",
    "PerformanceFinding": ".templates.review_swarm",
    "ArchitectureFinding": ".templates.review_swarm",
    "ReviewType": ".templates.review_swarm",
    "Severity": ".templates.review_swarm",
    "ReviewStatus": ".templates.review_swarm",
    "review_code": ".templates.review_swarm",
    "review_code_sync": ".templates.review_swarm",
    "CodeReviewer": ".templates.review_swarm",
    "SecurityScanner": ".templates.review_swarm",
    "PerformanceAnalyzer": ".templates.review_swarm",
    "ArchitectureReviewer": ".templates.review_swarm",
    "StyleChecker": ".templates.review_swarm",
    "ReviewSynthesizer": ".templates.review_swarm",
    # --- arxiv_learning_swarm ---
    "ArxivLearningSwarm": ".arxiv_learning_swarm",
    "ArxivLearningConfig": ".arxiv_learning_swarm",
    "ArxivLearningResult": ".arxiv_learning_swarm",
    "LearningContent": ".arxiv_learning_swarm",
    "LearningSection": ".arxiv_learning_swarm",
    "Concept": ".arxiv_learning_swarm",
    "PaperInfo": ".arxiv_learning_swarm",
    "LearningDepth": ".arxiv_learning_swarm",
    "ContentStyle": ".arxiv_learning_swarm",
    "AudienceLevel": ".arxiv_learning_swarm",
    "learn_paper": ".arxiv_learning_swarm",
    "learn_paper_sync": ".arxiv_learning_swarm",
    "PaperFetcherAgent": ".arxiv_learning_swarm",
    "ConceptExtractorAgent": ".arxiv_learning_swarm",
    "IntuitionBuilderAgent": ".arxiv_learning_swarm",
    "MathSimplifierAgent": ".arxiv_learning_swarm",
    "ExampleGeneratorAgent": ".arxiv_learning_swarm",
    "ProgressiveBuilderAgent": ".arxiv_learning_swarm",
    "ContentPolisherAgent": ".arxiv_learning_swarm",
    # --- olympiad_learning_swarm ---
    "OlympiadLearningSwarm": ".olympiad_learning_swarm",
    "OlympiadLearningConfig": ".olympiad_learning_swarm",
    "OlympiadLearningResult": ".olympiad_learning_swarm",
    "Subject": ".olympiad_learning_swarm",
    "DifficultyTier": ".olympiad_learning_swarm",
    "LessonDepth": ".olympiad_learning_swarm",
    "TeachingMode": ".olympiad_learning_swarm",
    "BuildingBlock": ".olympiad_learning_swarm",
    "ConceptCore": ".olympiad_learning_swarm",
    "PatternEntry": ".olympiad_learning_swarm",
    "Problem": ".olympiad_learning_swarm",
    "StrategyCard": ".olympiad_learning_swarm",
    "MistakeEntry": ".olympiad_learning_swarm",
    "learn_topic": ".olympiad_learning_swarm",
    "learn_topic_sync": ".olympiad_learning_swarm",
    "CurriculumArchitectAgent": ".olympiad_learning_swarm",
    "ConceptDecomposerAgent": ".olympiad_learning_swarm",
    "PatternHunterAgent": ".olympiad_learning_swarm",
    "ProblemCrafterAgent": ".olympiad_learning_swarm",
    "SolutionStrategistAgent": ".olympiad_learning_swarm",
    "MistakeAnalyzerAgent": ".olympiad_learning_swarm",
    "ConnectionMapperAgent": ".olympiad_learning_swarm",
    "ContentAssemblerAgent": ".olympiad_learning_swarm",
    "UnifiedTopicAgent": ".olympiad_learning_swarm",
    # --- perspective_learning_swarm ---
    "PerspectiveLearningSwarm": ".perspective_learning_swarm",
    "PerspectiveLearningConfig": ".perspective_learning_swarm",
    "PerspectiveLearningResult": ".perspective_learning_swarm",
    "PerspectiveType": ".perspective_learning_swarm",
    "Language": ".perspective_learning_swarm",
    "AgeGroup": ".perspective_learning_swarm",
    "ContentDepth": ".perspective_learning_swarm",
    "PerspectiveSection": ".perspective_learning_swarm",
    "LanguageContent": ".perspective_learning_swarm",
    "DebatePoint": ".perspective_learning_swarm",
    "ProjectActivity": ".perspective_learning_swarm",
    "FrameworkModel": ".perspective_learning_swarm",
    "teach_perspectives": ".perspective_learning_swarm",
    "teach_perspectives_sync": ".perspective_learning_swarm",
    "CurriculumDesignerAgent": ".perspective_learning_swarm",
    "IntuitiveExplainerAgent": ".perspective_learning_swarm",
    "FrameworkBuilderAgent": ".perspective_learning_swarm",
    "StorytellerAgent": ".perspective_learning_swarm",
    "DebateArchitectAgent": ".perspective_learning_swarm",
    "ProjectDesignerAgent": ".perspective_learning_swarm",
    "RealWorldConnectorAgent": ".perspective_learning_swarm",
    "MultilingualAgent": ".perspective_learning_swarm",
    "NarrativeEditorAgent": ".perspective_learning_swarm",
    # --- pilot_swarm ---
    "PilotSwarm": ".pilot_swarm",
    "PilotConfig": ".pilot_swarm",
    "PilotResult": ".pilot_swarm",
    "SubtaskType": ".pilot_swarm",
    "SubtaskStatus": ".pilot_swarm",
    "Subtask": ".pilot_swarm",
    "pilot": ".pilot_swarm",
    "pilot_sync": ".pilot_swarm",
    "PilotPlannerAgent": ".pilot_swarm",
    "PilotSearchAgent": ".pilot_swarm",
    "PilotCoderAgent": ".pilot_swarm",
    "PilotTerminalAgent": ".pilot_swarm",
    "PilotSkillWriterAgent": ".pilot_swarm",
    "PilotValidatorAgent": ".pilot_swarm",
    # --- learning_swarm ---
    "LearningSwarm": ".templates.learning_swarm",
    "LearningConfig": ".templates.learning_swarm",
    "LearningResult": ".templates.learning_swarm",
    "SwarmPerformance": ".templates.learning_swarm",
    "OptimizationResult": ".templates.learning_swarm",
    "LearningMode": ".templates.learning_swarm",
    "OptimizationType": ".templates.learning_swarm",
    "improve_swarm": ".templates.learning_swarm",
    "improve_swarm_sync": ".templates.learning_swarm",
    "PerformanceEvaluator": ".templates.learning_swarm",
    "GoldCurator": ".templates.learning_swarm",
    "PromptOptimizer": ".templates.learning_swarm",
    "WorkflowOptimizer": ".templates.learning_swarm",
    "ParameterTuner": ".templates.learning_swarm",
    "MetaLearner": ".templates.learning_swarm",
    # --- topic_research_swarm ---
    "TopicResearchSwarm": ".topic_research_swarm",
    "TopicResearchConfig": ".topic_research_swarm",
    "TopicResearchResult": ".topic_research_swarm",
    "ResearchDepth": ".topic_research_swarm",
    "ResearchMode": ".topic_research_swarm",
    "ResearchFinding": ".topic_research_swarm",
    "SourceReference": ".topic_research_swarm",
    "ComparisonDimension": ".topic_research_swarm",
    "topic_research": ".topic_research_swarm",
    "topic_research_sync": ".topic_research_swarm",
    "TopicDecomposerAgent": ".topic_research_swarm",
    "WebResearcherAgent": ".topic_research_swarm",
    "DataSynthesizerAgent": ".topic_research_swarm",
    "ComparativeAnalystAgent": ".topic_research_swarm",
    "ReportCompilerAgent": ".topic_research_swarm",
    "FactCheckerAgent": ".topic_research_swarm",
}


def __getattr__(name: str) -> Any:
    if name in _LAZY_IMPORTS:
        module_path = _LAZY_IMPORTS[name]
        module = _importlib.import_module(module_path, __name__)
        value = getattr(module, name)
        globals()[name] = value  # cache for subsequent access
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    # Base (eager) — new preferred names
    "SwarmTemplate",
    "AgentCoordinator",
    "CoordinationResult",
    # Base (eager) — backward compat
    "TeamCoordinator",
    "TeamResult",
    # Shared
    "AgentSpec",
    "CoordinationPattern",
    "MergeStrategy",
    # Lazy (all swarm names)
    *_LAZY_IMPORTS.keys(),
]
