"""
Jotty Swarm Templates
=====================

All swarms are **lazily loaded** — importing ``core.swarms`` does NOT
trigger heavy dependency chains.  A swarm module is only loaded on
first attribute access (e.g. ``from core.swarms import CodingSwarm``).

Available Swarms:
    ResearchSwarm, FundamentalSwarm, DataAnalysisSwarm,
    CodingSwarm, TestingSwarm, ReviewSwarm,
    IdeaWriterSwarm, DevOpsSwarm,
    ArxivLearningSwarm, OlympiadLearningSwarm, PerspectiveLearningSwarm, LearningSwarm

Quick usage::

    from core.swarms import CodingSwarm, code
    result = await code("Create a REST API")
"""

import importlib as _importlib
from typing import Any

# =========================================================================
# EAGER: Base infrastructure (lightweight, needed everywhere)
# =========================================================================
from .base import (
    DomainSwarm,
    AgentTeam,
    AgentSpec,
    TeamResult,
    CoordinationPattern,
    MergeStrategy,
)

from .base_swarm import (
    AgentRole,
    EvaluationResult,
    ImprovementType,
    GoldStandard,
    Evaluation,
    ImprovementSuggestion,
    SwarmAgentConfig,
    ExecutionTrace,
    SwarmBaseConfig,
    SwarmResult,
    GoldStandardDB,
    ImprovementHistory,
    ExpertAgent,
    ReviewerAgent,
    PlannerAgent,
    ActorAgent,
    BaseSwarm,
    SwarmRegistry,
    register_swarm,
)

# =========================================================================
# LAZY: Swarm modules — loaded on first access via __getattr__
# =========================================================================

_LAZY_IMPORTS: dict[str, str] = {
    # --- swarm_signatures (DSPy-dependent, loaded lazily) ---
    "ExpertEvaluationSignature": ".swarm_signatures",
    "ReviewerAnalysisSignature": ".swarm_signatures",
    "PlannerOptimizationSignature": ".swarm_signatures",
    "ActorExecutionSignature": ".swarm_signatures",
    "AuditorVerificationSignature": ".swarm_signatures",
    "LearnerExtractionSignature": ".swarm_signatures",
    # --- research_swarm ---
    "ResearchSwarm": ".research_swarm",
    "ResearchConfig": ".research_swarm",
    "ResearchResult": ".research_swarm",
    "RatingType": ".research_swarm",
    "research": ".research_swarm",
    "research_sync": ".research_swarm",
    "BaseSwarmAgent": ".research_swarm",
    "DataFetcherAgent": ".research_swarm",
    "WebSearchAgent": ".research_swarm",
    "SentimentAgent": ".research_swarm",
    "LLMAnalysisAgent": ".research_swarm",
    "PeerComparisonAgent": ".research_swarm",
    "ChartGeneratorAgent": ".research_swarm",
    "ReportGeneratorAgent": ".research_swarm",
    "TechnicalAnalysisAgent": ".research_swarm",
    "EnhancedChartGeneratorAgent": ".research_swarm",
    "ScreenerAgent": ".research_swarm",
    "SocialSentimentAgent": ".research_swarm",
    "StockAnalysisSignature": ".research_swarm",
    "SentimentAnalysisSignature": ".research_swarm",
    "PeerSelectionSignature": ".research_swarm",
    "SocialSentimentSignature": ".research_swarm",
    "TechnicalSignalsSignature": ".research_swarm",
    # --- coding_swarm ---
    "CodingSwarm": ".coding_swarm",
    "CodingConfig": ".coding_swarm",
    "CodingResult": ".coding_swarm",
    "CodeOutput": ".coding_swarm",
    "CodeLanguage": ".coding_swarm",
    "CodeStyle": ".coding_swarm",
    "code": ".coding_swarm",
    "code_sync": ".coding_swarm",
    "ArchitectAgent": ".coding_swarm",
    "DeveloperAgent": ".coding_swarm",
    "DebuggerAgent": ".coding_swarm",
    "OptimizerAgent": ".coding_swarm",
    "TestWriterAgent": ".coding_swarm",
    "DocWriterAgent": ".coding_swarm",
    # --- testing_swarm ---
    "TestingSwarm": ".testing_swarm",
    "TestingConfig": ".testing_swarm",
    "TestingResult": ".testing_swarm",
    "TestSuite": ".testing_swarm",
    "TestCase": ".testing_swarm",
    "CoverageReport": ".testing_swarm",
    "TestType": ".testing_swarm",
    "TestFramework": ".testing_swarm",
    "CoverageTarget": ".testing_swarm",
    "test": ".testing_swarm",
    "test_sync": ".testing_swarm",
    "CodeAnalyzerAgent": ".testing_swarm",
    "UnitTestAgent": ".testing_swarm",
    "IntegrationTestAgent": ".testing_swarm",
    "E2ETestAgent": ".testing_swarm",
    "CoverageAgent": ".testing_swarm",
    "QualityAgent": ".testing_swarm",
    # --- fundamental_swarm ---
    "FundamentalSwarm": ".fundamental_swarm",
    "FundamentalConfig": ".fundamental_swarm",
    "FundamentalResult": ".fundamental_swarm",
    "FinancialMetrics": ".fundamental_swarm",
    "ValuationMetrics": ".fundamental_swarm",
    "QualityMetrics": ".fundamental_swarm",
    "ValuationResult": ".fundamental_swarm",
    "InvestmentThesis": ".fundamental_swarm",
    "ValuationType": ".fundamental_swarm",
    "InvestmentStyle": ".fundamental_swarm",
    "RatingScale": ".fundamental_swarm",
    "analyze_fundamentals": ".fundamental_swarm",
    "analyze_fundamentals_sync": ".fundamental_swarm",
    "FinancialStatementAgent": ".fundamental_swarm",
    "RatioAnalysisAgent": ".fundamental_swarm",
    "ValuationAgent": ".fundamental_swarm",
    "QualityEarningsAgent": ".fundamental_swarm",
    "ManagementAgent": ".fundamental_swarm",
    "MoatAgent": ".fundamental_swarm",
    "ThesisAgent": ".fundamental_swarm",
    # --- idea_writer_swarm ---
    "IdeaWriterSwarm": ".idea_writer_swarm",
    "WriterConfig": ".idea_writer_swarm",
    "WriterResult": ".idea_writer_swarm",
    "ContentResult": ".idea_writer_swarm",
    "Section": ".idea_writer_swarm",
    "Outline": ".idea_writer_swarm",
    "ContentType": ".idea_writer_swarm",
    "Tone": ".idea_writer_swarm",
    "OutputFormat": ".idea_writer_swarm",
    "write": ".idea_writer_swarm",
    "write_sync": ".idea_writer_swarm",
    "SectionRegistry": ".idea_writer_swarm",
    "SectionWriter": ".idea_writer_swarm",
    "IntroductionWriter": ".idea_writer_swarm",
    "BodySectionWriter": ".idea_writer_swarm",
    "ConclusionWriter": ".idea_writer_swarm",
    "MarketAnalysisWriter": ".idea_writer_swarm",
    "CaseStudiesWriter": ".idea_writer_swarm",
    "TechnicalDeepDiveWriter": ".idea_writer_swarm",
    "ResearchFindingsWriter": ".idea_writer_swarm",
    "OutlineAgent": ".idea_writer_swarm",
    "ResearchAgent": ".idea_writer_swarm",
    "PolishAgent": ".idea_writer_swarm",
    # --- data_analysis_swarm ---
    "DataAnalysisSwarm": ".data_analysis_swarm",
    "DataAnalysisConfig": ".data_analysis_swarm",
    "AnalysisResult": ".data_analysis_swarm",
    "DataProfile": ".data_analysis_swarm",
    "StatisticalResult": ".data_analysis_swarm",
    "Insight": ".data_analysis_swarm",
    "MLRecommendation": ".data_analysis_swarm",
    "Visualization": ".data_analysis_swarm",
    "AnalysisType": ".data_analysis_swarm",
    "DataType": ".data_analysis_swarm",
    "VisualizationType": ".data_analysis_swarm",
    "analyze_data": ".data_analysis_swarm",
    "analyze_data_sync": ".data_analysis_swarm",
    "DataProfilerAgent": ".data_analysis_swarm",
    "EDAAgent": ".data_analysis_swarm",
    "StatisticalAgent": ".data_analysis_swarm",
    "InsightAgent": ".data_analysis_swarm",
    "MLRecommenderAgent": ".data_analysis_swarm",
    "VisualizationAgent": ".data_analysis_swarm",
    # --- devops_swarm ---
    "DevOpsSwarm": ".devops_swarm",
    "DevOpsConfig": ".devops_swarm",
    "DevOpsResult": ".devops_swarm",
    "InfrastructureSpec": ".devops_swarm",
    "PipelineSpec": ".devops_swarm",
    "ContainerSpec": ".devops_swarm",
    "SecurityConfig": ".devops_swarm",
    "MonitoringConfig": ".devops_swarm",
    "CloudProvider": ".devops_swarm",
    "IaCTool": ".devops_swarm",
    "CIProvider": ".devops_swarm",
    "ContainerPlatform": ".devops_swarm",
    "deploy": ".devops_swarm",
    "deploy_sync": ".devops_swarm",
    "InfrastructureArchitect": ".devops_swarm",
    "CICDDesigner": ".devops_swarm",
    "ContainerSpecialist": ".devops_swarm",
    "SecurityHardener": ".devops_swarm",
    "MonitoringSpecialist": ".devops_swarm",
    "IaCGenerator": ".devops_swarm",
    # --- review_swarm ---
    "ReviewSwarm": ".review_swarm",
    "ReviewConfig": ".review_swarm",
    "ReviewResult": ".review_swarm",
    "ReviewComment": ".review_swarm",
    "SecurityFinding": ".review_swarm",
    "PerformanceFinding": ".review_swarm",
    "ArchitectureFinding": ".review_swarm",
    "ReviewType": ".review_swarm",
    "Severity": ".review_swarm",
    "ReviewStatus": ".review_swarm",
    "review_code": ".review_swarm",
    "review_code_sync": ".review_swarm",
    "CodeReviewer": ".review_swarm",
    "SecurityScanner": ".review_swarm",
    "PerformanceAnalyzer": ".review_swarm",
    "ArchitectureReviewer": ".review_swarm",
    "StyleChecker": ".review_swarm",
    "ReviewSynthesizer": ".review_swarm",
    # --- arxiv_learning_swarm ---
    "ArxivLearningSwarm": ".arxiv_learning_swarm",
    "ArxivLearningConfig": ".arxiv_learning_swarm",
    "ArxivLearningResult": ".arxiv_learning_swarm",
    "LearningContent": ".arxiv_learning_swarm",
    "LearningSection": ".arxiv_learning_swarm",
    "Concept": ".arxiv_learning_swarm",
    "PaperInfo": ".arxiv_learning_swarm",
    "LearningDepth": ".arxiv_learning_swarm",
    "ContentStyle": ".arxiv_learning_swarm",
    "AudienceLevel": ".arxiv_learning_swarm",
    "learn_paper": ".arxiv_learning_swarm",
    "learn_paper_sync": ".arxiv_learning_swarm",
    "PaperFetcherAgent": ".arxiv_learning_swarm",
    "ConceptExtractorAgent": ".arxiv_learning_swarm",
    "IntuitionBuilderAgent": ".arxiv_learning_swarm",
    "MathSimplifierAgent": ".arxiv_learning_swarm",
    "ExampleGeneratorAgent": ".arxiv_learning_swarm",
    "ProgressiveBuilderAgent": ".arxiv_learning_swarm",
    "ContentPolisherAgent": ".arxiv_learning_swarm",
    # --- olympiad_learning_swarm ---
    "OlympiadLearningSwarm": ".olympiad_learning_swarm",
    "OlympiadLearningConfig": ".olympiad_learning_swarm",
    "OlympiadLearningResult": ".olympiad_learning_swarm",
    "Subject": ".olympiad_learning_swarm",
    "DifficultyTier": ".olympiad_learning_swarm",
    "LessonDepth": ".olympiad_learning_swarm",
    "TeachingMode": ".olympiad_learning_swarm",
    "BuildingBlock": ".olympiad_learning_swarm",
    "ConceptCore": ".olympiad_learning_swarm",
    "PatternEntry": ".olympiad_learning_swarm",
    "Problem": ".olympiad_learning_swarm",
    "StrategyCard": ".olympiad_learning_swarm",
    "MistakeEntry": ".olympiad_learning_swarm",
    "learn_topic": ".olympiad_learning_swarm",
    "learn_topic_sync": ".olympiad_learning_swarm",
    "CurriculumArchitectAgent": ".olympiad_learning_swarm",
    "ConceptDecomposerAgent": ".olympiad_learning_swarm",
    "PatternHunterAgent": ".olympiad_learning_swarm",
    "ProblemCrafterAgent": ".olympiad_learning_swarm",
    "SolutionStrategistAgent": ".olympiad_learning_swarm",
    "MistakeAnalyzerAgent": ".olympiad_learning_swarm",
    "ConnectionMapperAgent": ".olympiad_learning_swarm",
    "ContentAssemblerAgent": ".olympiad_learning_swarm",
    "UnifiedTopicAgent": ".olympiad_learning_swarm",
    # --- perspective_learning_swarm ---
    "PerspectiveLearningSwarm": ".perspective_learning_swarm",
    "PerspectiveLearningConfig": ".perspective_learning_swarm",
    "PerspectiveLearningResult": ".perspective_learning_swarm",
    "PerspectiveType": ".perspective_learning_swarm",
    "Language": ".perspective_learning_swarm",
    "AgeGroup": ".perspective_learning_swarm",
    "ContentDepth": ".perspective_learning_swarm",
    "PerspectiveSection": ".perspective_learning_swarm",
    "LanguageContent": ".perspective_learning_swarm",
    "DebatePoint": ".perspective_learning_swarm",
    "ProjectActivity": ".perspective_learning_swarm",
    "FrameworkModel": ".perspective_learning_swarm",
    "teach_perspectives": ".perspective_learning_swarm",
    "teach_perspectives_sync": ".perspective_learning_swarm",
    "CurriculumDesignerAgent": ".perspective_learning_swarm",
    "IntuitiveExplainerAgent": ".perspective_learning_swarm",
    "FrameworkBuilderAgent": ".perspective_learning_swarm",
    "StorytellerAgent": ".perspective_learning_swarm",
    "DebateArchitectAgent": ".perspective_learning_swarm",
    "ProjectDesignerAgent": ".perspective_learning_swarm",
    "RealWorldConnectorAgent": ".perspective_learning_swarm",
    "MultilingualAgent": ".perspective_learning_swarm",
    "NarrativeEditorAgent": ".perspective_learning_swarm",
    # --- learning_swarm ---
    "LearningSwarm": ".learning_swarm",
    "LearningConfig": ".learning_swarm",
    "LearningResult": ".learning_swarm",
    "SwarmPerformance": ".learning_swarm",
    "OptimizationResult": ".learning_swarm",
    "LearningMode": ".learning_swarm",
    "OptimizationType": ".learning_swarm",
    "improve_swarm": ".learning_swarm",
    "improve_swarm_sync": ".learning_swarm",
    "PerformanceEvaluator": ".learning_swarm",
    "GoldCurator": ".learning_swarm",
    "PromptOptimizer": ".learning_swarm",
    "WorkflowOptimizer": ".learning_swarm",
    "ParameterTuner": ".learning_swarm",
    "MetaLearner": ".learning_swarm",
}


def __getattr__(name: str) -> Any:
    if name in _LAZY_IMPORTS:
        module_path = _LAZY_IMPORTS[name]
        module = _importlib.import_module(module_path, __name__)
        value = getattr(module, name)
        globals()[name] = value  # cache for subsequent access
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    # Base (eager)
    "DomainSwarm", "AgentTeam", "AgentSpec", "TeamResult",
    "CoordinationPattern", "MergeStrategy",
    "AgentRole", "EvaluationResult", "ImprovementType",
    "GoldStandard", "Evaluation", "ImprovementSuggestion",
    "SwarmAgentConfig", "ExecutionTrace", "SwarmBaseConfig", "SwarmResult",
    "ExpertEvaluationSignature", "ReviewerAnalysisSignature",
    "PlannerOptimizationSignature", "ActorExecutionSignature",
    "GoldStandardDB", "ImprovementHistory",
    "ExpertAgent", "ReviewerAgent", "PlannerAgent", "ActorAgent",
    "BaseSwarm", "SwarmRegistry", "register_swarm",
    # Lazy (all swarm names)
    *_LAZY_IMPORTS.keys(),
]
