"""Topic Research Swarm — PPTX Generator.

Converts structured TopicResearchResult into a professional PowerPoint
presentation using python-pptx. Design: dark navy theme with accent colors,
executive-quality layout.

Usage (internal — called by swarm when generate_pptx=True):
    from .pptx_generator import generate_research_pptx
    pptx_path = generate_research_pptx(result, output_dir="/tmp")
"""

from __future__ import annotations

import logging
import re
import textwrap
from pathlib import Path
from typing import TYPE_CHECKING, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

if TYPE_CHECKING:
    from .types import TopicResearchResult

# ═══════════════════════════════════════════════════════════════════════════════
# DESIGN CONSTANTS
# ═══════════════════════════════════════════════════════════════════════════════

# Colors (RGB tuples)
NAVY = (11, 29, 58)  # Dark navy background
WHITE = (255, 255, 255)
LIGHT_GRAY = (189, 195, 209)
ACCENT_BLUE = (0, 150, 255)
ACCENT_GREEN = (0, 200, 130)
ACCENT_ORANGE = (255, 165, 0)
ACCENT_RED = (220, 50, 50)
DARK_CARD = (18, 42, 82)
MEDIUM_NAVY = (25, 55, 100)

# Slide dimensions (widescreen 16:9)
SLIDE_WIDTH_INCHES = 13.333
SLIDE_HEIGHT_INCHES = 7.5


def generate_research_pptx(
    result: "TopicResearchResult",
    output_dir: str = ".",
    filename: Optional[str] = None,
) -> str:
    """Generate a professional PPTX from research results.

    Args:
        result: TopicResearchResult from the swarm.
        output_dir: Directory to save the PPTX.
        filename: Optional filename (without extension).

    Returns:
        Path to the generated PPTX file.
    """
    try:
        from pptx import Presentation
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN
        from pptx.util import Inches, Pt
    except ImportError:
        logger.error("python-pptx not installed. Run: pip install python-pptx")
        return ""

    prs = Presentation()
    prs.slide_width = Inches(SLIDE_WIDTH_INCHES)
    prs.slide_height = Inches(SLIDE_HEIGHT_INCHES)

    # Helper functions
    def _rgb(color: Tuple[int, int, int]) -> RGBColor:
        return RGBColor(*color)

    def _add_bg(slide, color: Tuple[int, int, int] = NAVY):
        bg = slide.background
        fill = bg.fill
        fill.solid()
        fill.fore_color.rgb = _rgb(color)

    def _add_box(slide, left, top, width, height, color=DARK_CARD, border=None):
        shape = slide.shapes.add_shape(1, Inches(left), Inches(top), Inches(width), Inches(height))
        shape.fill.solid()
        shape.fill.fore_color.rgb = _rgb(color)
        if border:
            shape.line.color.rgb = _rgb(border)
            shape.line.width = Pt(1)
        else:
            shape.line.fill.background()
        return shape

    def _add_text(
        slide,
        text,
        left,
        top,
        width,
        height,
        font_size=14,
        color=WHITE,
        bold=False,
        align=PP_ALIGN.LEFT,
        font_name="Calibri",
    ):
        txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
        tf = txBox.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = text
        p.font.size = Pt(font_size)
        p.font.color.rgb = _rgb(color)
        p.font.bold = bold
        p.font.name = font_name
        p.alignment = align
        return txBox

    def _add_multiline(
        slide,
        lines,
        left,
        top,
        width,
        height,
        font_size=12,
        color=WHITE,
        line_spacing=1.2,
        bullet=False,
        font_name="Calibri",
    ):
        txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
        tf = txBox.text_frame
        tf.word_wrap = True
        for i, line in enumerate(lines):
            if i == 0:
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()
            display = f"  {line}" if bullet else line
            p.text = display
            p.font.size = Pt(font_size)
            p.font.color.rgb = _rgb(color)
            p.font.name = font_name
            p.space_after = Pt(font_size * (line_spacing - 1) + 2)
        return txBox

    def _footer(slide, text="Generated by Jotty TopicResearchSwarm"):
        _add_text(
            slide,
            text,
            0.5,
            7.0,
            12,
            0.4,
            font_size=8,
            color=LIGHT_GRAY,
            align=PP_ALIGN.RIGHT,
        )

    def _slide_num(slide, num):
        _add_text(
            slide,
            str(num),
            12.5,
            7.0,
            0.5,
            0.4,
            font_size=8,
            color=LIGHT_GRAY,
            align=PP_ALIGN.RIGHT,
        )

    # ── Parse markdown report into sections ──────────────────────────────
    sections = _parse_markdown_sections(result.report_markdown)

    slide_num = 0

    # ══════════════════════════════════════════════════════════════════════
    # SLIDE 1: TITLE
    # ══════════════════════════════════════════════════════════════════════
    slide_num += 1
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # Blank
    _add_bg(slide)

    # Accent line
    _add_box(slide, 1, 2.2, 3, 0.05, color=ACCENT_BLUE)

    _add_text(
        slide,
        result.topic.upper(),
        1,
        2.4,
        11,
        1.2,
        font_size=36,
        bold=True,
        color=WHITE,
    )

    # Subtitle with mode/depth
    mode_label = result.mode.replace("_", " ").title()
    depth_label = result.depth.title()
    subtitle = f"{mode_label} Research | {depth_label} Depth"
    if result.comparison_entities:
        subtitle += f" | {' vs '.join(result.comparison_entities)}"
    _add_text(
        slide,
        subtitle,
        1,
        3.6,
        11,
        0.5,
        font_size=16,
        color=ACCENT_BLUE,
    )

    # Stats bar
    stats = []
    if result.sub_topics:
        stats.append(f"{len(result.sub_topics)} Sub-topics")
    if result.total_sources_consulted:
        stats.append(f"{result.total_sources_consulted} Sources")
    if result.key_findings:
        stats.append(f"{len(result.key_findings)} Key Findings")
    if result.fact_check_score:
        stats.append(f"{result.fact_check_score:.0%} Fact-Check Score")
    stats.append(f"{result.execution_time:.0f}s Runtime")

    _add_text(
        slide,
        "  |  ".join(stats),
        1,
        4.4,
        11,
        0.4,
        font_size=11,
        color=LIGHT_GRAY,
    )
    _footer(slide)
    _slide_num(slide, slide_num)

    # ══════════════════════════════════════════════════════════════════════
    # SLIDE 2: EXECUTIVE SUMMARY
    # ══════════════════════════════════════════════════════════════════════
    slide_num += 1
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_bg(slide)
    _add_text(
        slide,
        "EXECUTIVE SUMMARY",
        0.5,
        0.3,
        12,
        0.6,
        font_size=24,
        bold=True,
        color=WHITE,
    )
    _add_box(slide, 0.5, 0.9, 4, 0.04, color=ACCENT_BLUE)

    # One-liner thesis
    if result.output.get("one_liner"):
        _add_box(slide, 0.5, 1.2, 12.3, 0.8, color=MEDIUM_NAVY, border=ACCENT_BLUE)
        _add_text(
            slide,
            result.output["one_liner"],
            0.8,
            1.3,
            11.7,
            0.6,
            font_size=14,
            color=ACCENT_BLUE,
            bold=True,
        )

    # Executive summary bullets
    summary_text = result.summary or result.output.get("executive_summary", "")
    if summary_text:
        bullets = _extract_bullets(summary_text)
        _add_multiline(
            slide,
            bullets[:8],
            0.8,
            2.2,
            11.5,
            4.5,
            font_size=13,
            color=WHITE,
            bullet=True,
        )

    _footer(slide)
    _slide_num(slide, slide_num)

    # ══════════════════════════════════════════════════════════════════════
    # SLIDE 3: SUB-TOPICS OVERVIEW
    # ══════════════════════════════════════════════════════════════════════
    if result.sub_topics:
        slide_num += 1
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        _add_bg(slide)
        _add_text(
            slide,
            "RESEARCH SCOPE",
            0.5,
            0.3,
            12,
            0.6,
            font_size=24,
            bold=True,
            color=WHITE,
        )
        _add_box(slide, 0.5, 0.9, 4, 0.04, color=ACCENT_GREEN)

        # Grid of sub-topic cards
        cols = 3
        card_w = 3.7
        card_h = 1.2
        x_start = 0.6
        y_start = 1.3
        x_gap = 0.35
        y_gap = 0.25

        for i, st in enumerate(result.sub_topics[:9]):  # Max 9
            col = i % cols
            row = i // cols
            x = x_start + col * (card_w + x_gap)
            y = y_start + row * (card_h + y_gap)
            _add_box(slide, x, y, card_w, card_h, color=DARK_CARD, border=ACCENT_GREEN)
            _add_text(
                slide,
                f"{i + 1}",
                x + 0.15,
                y + 0.15,
                0.4,
                0.4,
                font_size=20,
                color=ACCENT_GREEN,
                bold=True,
            )
            wrapped = textwrap.fill(st, width=35)
            _add_text(
                slide,
                wrapped,
                x + 0.5,
                y + 0.15,
                card_w - 0.7,
                card_h - 0.3,
                font_size=11,
                color=WHITE,
            )

        _footer(slide)
        _slide_num(slide, slide_num)

    # ══════════════════════════════════════════════════════════════════════
    # SLIDES 4+: KEY FINDINGS (one slide per ~4 findings)
    # ══════════════════════════════════════════════════════════════════════
    if result.key_findings:
        chunk_size = 5
        for chunk_start in range(0, len(result.key_findings), chunk_size):
            chunk = result.key_findings[chunk_start : chunk_start + chunk_size]
            slide_num += 1
            slide = prs.slides.add_slide(prs.slide_layouts[6])
            _add_bg(slide)
            page_label = (
                f" ({chunk_start + 1}-{chunk_start + len(chunk)})"
                if len(result.key_findings) > chunk_size
                else ""
            )
            _add_text(
                slide,
                f"KEY FINDINGS{page_label}",
                0.5,
                0.3,
                12,
                0.6,
                font_size=24,
                bold=True,
                color=WHITE,
            )
            _add_box(slide, 0.5, 0.9, 4, 0.04, color=ACCENT_ORANGE)

            for j, finding in enumerate(chunk):
                y = 1.2 + j * 1.1
                _add_box(slide, 0.5, y, 12.3, 0.95, color=DARK_CARD)
                # Number badge
                _add_box(slide, 0.6, y + 0.15, 0.5, 0.5, color=ACCENT_ORANGE)
                _add_text(
                    slide,
                    str(chunk_start + j + 1),
                    0.6,
                    y + 0.15,
                    0.5,
                    0.5,
                    font_size=16,
                    bold=True,
                    color=WHITE,
                    align=PP_ALIGN.CENTER,
                )
                # Finding text
                wrapped = textwrap.fill(finding, width=110)
                _add_text(
                    slide,
                    wrapped,
                    1.3,
                    y + 0.1,
                    11.2,
                    0.85,
                    font_size=12,
                    color=WHITE,
                )

            _footer(slide)
            _slide_num(slide, slide_num)

    # ══════════════════════════════════════════════════════════════════════
    # DETAILED FINDINGS BY SUB-TOPIC
    # ══════════════════════════════════════════════════════════════════════
    if result.detailed_findings:
        # Group by sub-topic
        by_topic: Dict[str, list] = {}
        for f in result.detailed_findings:
            key = f.sub_topic or "General"
            by_topic.setdefault(key, []).append(f)

        for st_name, findings in list(by_topic.items())[:8]:  # Max 8 sub-topics
            slide_num += 1
            slide = prs.slides.add_slide(prs.slide_layouts[6])
            _add_bg(slide)
            _add_text(
                slide,
                st_name.upper(),
                0.5,
                0.3,
                12,
                0.6,
                font_size=20,
                bold=True,
                color=WHITE,
            )
            _add_box(slide, 0.5, 0.85, 4, 0.04, color=ACCENT_BLUE)

            for j, f in enumerate(findings[:5]):  # Max 5 per slide
                y = 1.1 + j * 1.15
                conf_color = (
                    ACCENT_GREEN
                    if f.confidence >= 0.7
                    else ACCENT_ORANGE if f.confidence >= 0.4 else ACCENT_RED
                )
                _add_box(slide, 0.5, y, 12.3, 1.0, color=DARK_CARD)
                # Confidence badge
                _add_box(slide, 0.6, y + 0.2, 0.8, 0.5, color=conf_color)
                _add_text(
                    slide,
                    f"{f.confidence:.0%}",
                    0.6,
                    y + 0.2,
                    0.8,
                    0.5,
                    font_size=12,
                    bold=True,
                    color=WHITE,
                    align=PP_ALIGN.CENTER,
                )
                # Claim
                _add_text(
                    slide,
                    textwrap.fill(f.claim, width=90),
                    1.6,
                    y + 0.05,
                    10.9,
                    0.45,
                    font_size=12,
                    bold=True,
                    color=WHITE,
                )
                # Evidence
                if f.evidence:
                    _add_text(
                        slide,
                        textwrap.fill(f.evidence, width=100),
                        1.6,
                        y + 0.5,
                        10.9,
                        0.45,
                        font_size=10,
                        color=LIGHT_GRAY,
                    )

            _footer(slide)
            _slide_num(slide, slide_num)

    # ══════════════════════════════════════════════════════════════════════
    # COMPARISON MATRIX (if comparison mode)
    # ══════════════════════════════════════════════════════════════════════
    if result.comparison_matrix:
        slide_num += 1
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        _add_bg(slide)
        entities_str = " vs ".join(result.comparison_entities[:2])
        _add_text(
            slide,
            f"COMPARISON: {entities_str.upper()}",
            0.5,
            0.3,
            12,
            0.6,
            font_size=22,
            bold=True,
            color=WHITE,
        )
        _add_box(slide, 0.5, 0.9, 4, 0.04, color=ACCENT_ORANGE)

        # Table header
        y = 1.2
        _add_box(slide, 0.5, y, 3.0, 0.5, color=MEDIUM_NAVY)
        _add_text(
            slide,
            "DIMENSION",
            0.6,
            y + 0.05,
            2.8,
            0.4,
            font_size=11,
            bold=True,
            color=ACCENT_BLUE,
        )
        entities = result.comparison_entities[:2]
        for ei, ent in enumerate(entities):
            x = 3.8 + ei * 3.5
            _add_box(slide, x, y, 3.3, 0.5, color=MEDIUM_NAVY)
            _add_text(
                slide,
                ent.upper(),
                x + 0.1,
                y + 0.05,
                3.1,
                0.4,
                font_size=11,
                bold=True,
                color=ACCENT_BLUE,
                align=PP_ALIGN.CENTER,
            )
        # Winner column
        _add_box(slide, 11.0, y, 1.8, 0.5, color=MEDIUM_NAVY)
        _add_text(
            slide,
            "WINNER",
            11.0,
            y + 0.05,
            1.8,
            0.4,
            font_size=11,
            bold=True,
            color=ACCENT_GREEN,
            align=PP_ALIGN.CENTER,
        )

        # Rows
        for i, dim in enumerate(result.comparison_matrix[:10]):  # Max 10 rows
            y = 1.8 + i * 0.55
            row_bg = DARK_CARD if i % 2 == 0 else MEDIUM_NAVY
            _add_box(slide, 0.5, y, 3.0, 0.5, color=row_bg)
            _add_text(
                slide,
                dim.dimension,
                0.6,
                y + 0.05,
                2.8,
                0.4,
                font_size=10,
                bold=True,
                color=WHITE,
            )
            for ei, ent in enumerate(entities):
                x = 3.8 + ei * 3.5
                _add_box(slide, x, y, 3.3, 0.5, color=row_bg)
                score_text = dim.entity_scores.get(ent, "—")
                _add_text(
                    slide,
                    str(score_text)[:50],
                    x + 0.1,
                    y + 0.05,
                    3.1,
                    0.4,
                    font_size=10,
                    color=WHITE,
                    align=PP_ALIGN.CENTER,
                )
            # Winner
            _add_box(slide, 11.0, y, 1.8, 0.5, color=row_bg)
            winner_color = ACCENT_GREEN if dim.winner else LIGHT_GRAY
            _add_text(
                slide,
                dim.winner or "Tie",
                11.0,
                y + 0.05,
                1.8,
                0.4,
                font_size=10,
                bold=True,
                color=winner_color,
                align=PP_ALIGN.CENTER,
            )

        # Verdict
        if result.comparison_verdict:
            verd_y = 1.8 + min(len(result.comparison_matrix), 10) * 0.55 + 0.2
            _add_box(slide, 0.5, verd_y, 12.3, 0.7, color=MEDIUM_NAVY, border=ACCENT_GREEN)
            _add_text(
                slide,
                f"VERDICT: {result.comparison_verdict}",
                0.7,
                verd_y + 0.1,
                11.9,
                0.5,
                font_size=12,
                bold=True,
                color=ACCENT_GREEN,
            )

        _footer(slide)
        _slide_num(slide, slide_num)

    # ══════════════════════════════════════════════════════════════════════
    # MARKDOWN SECTIONS (from the report body)
    # ══════════════════════════════════════════════════════════════════════
    for sec_title, sec_body in sections[:12]:  # Max 12 section slides
        if not sec_body.strip():
            continue
        # Skip executive summary (already covered)
        if "executive" in sec_title.lower() and "summary" in sec_title.lower():
            continue

        slide_num += 1
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        _add_bg(slide)
        _add_text(
            slide,
            sec_title.upper(),
            0.5,
            0.3,
            12,
            0.6,
            font_size=20,
            bold=True,
            color=WHITE,
        )
        _add_box(slide, 0.5, 0.85, 4, 0.04, color=ACCENT_BLUE)

        # Parse content into bullets
        content_bullets = _extract_bullets(sec_body)
        if content_bullets:
            _add_multiline(
                slide,
                content_bullets[:12],
                0.7,
                1.1,
                11.8,
                5.8,
                font_size=11,
                color=WHITE,
                bullet=True,
            )

        _footer(slide)
        _slide_num(slide, slide_num)

    # ══════════════════════════════════════════════════════════════════════
    # SOURCES SLIDE
    # ══════════════════════════════════════════════════════════════════════
    if result.sources:
        slide_num += 1
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        _add_bg(slide)
        _add_text(
            slide,
            "SOURCES & REFERENCES",
            0.5,
            0.3,
            12,
            0.6,
            font_size=22,
            bold=True,
            color=WHITE,
        )
        _add_box(slide, 0.5, 0.9, 4, 0.04, color=ACCENT_BLUE)

        source_lines = []
        seen_urls = set()
        for s in result.sources:
            if s.url and s.url not in seen_urls:
                seen_urls.add(s.url)
                label = s.title or s.url
                source_lines.append(f"{label}  ({s.url})")
        source_lines = source_lines[:20]  # Max 20

        _add_multiline(
            slide,
            source_lines,
            0.7,
            1.2,
            12,
            5.5,
            font_size=9,
            color=LIGHT_GRAY,
            bullet=True,
        )

        # Stats
        _add_text(
            slide,
            f"{result.total_sources_consulted} sources | "
            f"{result.unique_domains} unique domains",
            0.5,
            6.8,
            12,
            0.3,
            font_size=10,
            color=ACCENT_BLUE,
        )

        _footer(slide)
        _slide_num(slide, slide_num)

    # ══════════════════════════════════════════════════════════════════════
    # QUALITY SCORECARD
    # ══════════════════════════════════════════════════════════════════════
    slide_num += 1
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_bg(slide)
    _add_text(
        slide,
        "RESEARCH QUALITY SCORECARD",
        0.5,
        0.3,
        12,
        0.6,
        font_size=22,
        bold=True,
        color=WHITE,
    )
    _add_box(slide, 0.5, 0.9, 4, 0.04, color=ACCENT_GREEN)

    scores = [
        ("Fact-Check Score", result.fact_check_score),
        ("Completeness", result.completeness_score),
        ("Sources Consulted", result.total_sources_consulted),
        ("Unique Domains", result.unique_domains),
        ("Key Findings", len(result.key_findings)),
        ("Sub-topics Covered", len(result.sub_topics)),
        ("Execution Time", f"{result.execution_time:.0f}s"),
    ]
    for i, (label, value) in enumerate(scores):
        y = 1.3 + i * 0.7
        _add_box(slide, 1, y, 5, 0.55, color=DARK_CARD)
        _add_text(
            slide,
            label,
            1.2,
            y + 0.08,
            3,
            0.4,
            font_size=13,
            color=WHITE,
        )
        display = f"{value:.0%}" if isinstance(value, float) else str(value)
        score_color = (
            ACCENT_GREEN
            if isinstance(value, float) and value >= 0.7
            else ACCENT_ORANGE if isinstance(value, float) and value >= 0.4 else WHITE
        )
        _add_text(
            slide,
            display,
            4.2,
            y + 0.08,
            1.5,
            0.4,
            font_size=15,
            bold=True,
            color=score_color,
            align=PP_ALIGN.RIGHT,
        )

    # Agent contributions pie-chart style (text-based)
    if result.agent_contributions:
        _add_text(
            slide,
            "AGENT CONTRIBUTIONS",
            7.5,
            1.1,
            5,
            0.4,
            font_size=14,
            bold=True,
            color=ACCENT_BLUE,
        )
        agent_colors = [ACCENT_BLUE, ACCENT_GREEN, ACCENT_ORANGE, WHITE, LIGHT_GRAY, ACCENT_RED]
        for i, (agent, contrib) in enumerate(result.agent_contributions.items()):
            if contrib <= 0:
                continue
            y = 1.7 + i * 0.55
            bar_w = contrib * 4.5  # Scale to max 4.5 inches
            _add_box(slide, 7.5, y, bar_w, 0.35, color=agent_colors[i % len(agent_colors)])
            _add_text(
                slide,
                f"{agent.title()} ({contrib:.0%})",
                7.6,
                y + 0.02,
                4,
                0.3,
                font_size=10,
                bold=True,
                color=NAVY,
            )

    _footer(slide)
    _slide_num(slide, slide_num)

    # ── Save ─────────────────────────────────────────────────────────────
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    if not filename:
        safe_name = "".join(
            c if c.isalnum() or c in " -_" else "_" for c in result.topic[:60]
        ).strip()
        filename = f"{safe_name}_Research"

    pptx_path = str(output_path / f"{filename}.pptx")
    prs.save(pptx_path)
    logger.info(f"PPTX saved to {pptx_path} ({slide_num} slides)")
    return pptx_path


# ═══════════════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════════════


def _parse_markdown_sections(
    markdown: str,
) -> List[Tuple[str, str]]:
    """Parse markdown into (heading, body) sections."""
    if not markdown:
        return []

    sections: List[Tuple[str, str]] = []
    current_heading = ""
    current_body: List[str] = []

    for line in markdown.split("\n"):
        heading_match = re.match(r"^#{1,3}\s+(.+)$", line)
        if heading_match:
            if current_heading or current_body:
                sections.append((current_heading, "\n".join(current_body)))
            current_heading = heading_match.group(1).strip()
            current_body = []
        else:
            current_body.append(line)

    if current_heading or current_body:
        sections.append((current_heading, "\n".join(current_body)))

    return sections


def _extract_bullets(text: str) -> List[str]:
    """Extract bullet points from markdown text."""
    bullets = []
    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue
        # Remove markdown bullet markers
        line = re.sub(r"^[-*+]\s+", "", line)
        # Remove markdown bold
        line = re.sub(r"\*\*(.+?)\*\*", r"\1", line)
        # Remove markdown links
        line = re.sub(r"\[(.+?)\]\(.+?\)", r"\1", line)
        if line and len(line) > 5:
            bullets.append(line)
    return bullets
