#!/usr/bin/env python3
"""
Poodle for Dummies - Comprehensive Guide
Generated by Jotty Multi-Agent System with REAL LLM
"""

import sys
from pathlib import Path
import dspy

# Add Jotty to path
sys.path.insert(0, str(Path(__file__).parent))

from core.tools.content_generation import Document, SectionType, ContentGenerators
from core.integration.direct_claude_cli_lm import DirectClaudeCLI


# =============================================================================
# GENERIC COMPREHENSIVE GUIDE EXPERT SIGNATURE
# =============================================================================

class ComprehensiveGuideExpertSignature(dspy.Signature):
    """Expert that creates comprehensive beginner's guides on ANY topic"""
    topic: str = dspy.InputField(desc="Topic to create guide about (e.g., 'Poodles', 'Python Programming', 'Home Gardening')")
    goal: str = dspy.InputField(desc="Specific goal or focus for the guide")

    # Core Sections (applicable to most topics)
    introduction: str = dspy.OutputField(desc="Engaging introduction for complete beginners. IMPORTANT: Write in flowing paragraphs without hard line breaks. Use natural paragraph breaks only.")

    history: str = dspy.OutputField(desc="History, background, or origin of the topic. Write in flowing paragraphs.")

    fundamentals: str = dspy.OutputField(desc="Fundamental concepts, types, or categories. Write in flowing paragraphs.")

    characteristics: str = dspy.OutputField(desc="Key characteristics, features, or attributes. Write in flowing paragraphs.")

    maintenance: str = dspy.OutputField(desc="Care, maintenance, or ongoing requirements. Write in flowing paragraphs.")

    benefits: str = dspy.OutputField(desc="Benefits, advantages, or positive aspects. Write in flowing paragraphs.")

    skills: str = dspy.OutputField(desc="Required skills, knowledge, or abilities. Write in flowing paragraphs.")

    health_safety: str = dspy.OutputField(desc="Health, safety, or risk considerations. Write in flowing paragraphs.")

    resources: str = dspy.OutputField(desc="Resources, materials, or supplies needed. Write in flowing paragraphs.")

    getting_started: str = dspy.OutputField(desc="How to get started or begin. Write in flowing paragraphs.")

    best_practices: str = dspy.OutputField(desc="Best practices, tips, and techniques. Write in flowing paragraphs.")

    common_issues: str = dspy.OutputField(desc="Common issues, challenges, or mistakes to avoid. Write in flowing paragraphs.")

    community: str = dspy.OutputField(desc="Community, social aspects, or relationship considerations. Write in flowing paragraphs.")

    environment: str = dspy.OutputField(desc="Environmental or situational considerations. Write in flowing paragraphs.")

    selection: str = dspy.OutputField(desc="How to choose, select, or make decisions. Write in flowing paragraphs.")

    costs: str = dspy.OutputField(desc="Financial considerations, costs, and budgeting. CRITICAL: Write in continuous flowing paragraphs. Do NOT use hard line breaks within paragraphs. Use proper paragraph separation only.")

    conclusion: str = dspy.OutputField(desc="Summary and final advice for beginners. Write in flowing paragraphs.")


def configure_llm():
    """Configure Jotty's LLM provider"""
    import os

    print("🔧 Configuring DSPy LLM Provider...\n")

    # Try different providers in order of availability

    # 1. Try Claude CLI first (no API key needed!)
    print("   Checking Claude CLI...")
    try:
        lm = DirectClaudeCLI(model="haiku")  # Use Haiku for faster responses
        dspy.configure(lm=lm)
        print("   ✅ Configured with Claude CLI (Haiku model)")
        print("      Using local Claude Code CLI - no API key needed!\n")
        return True
    except RuntimeError as e:
        if "not installed" in str(e):
            print(f"   ⚠️  Claude CLI not installed")
            print(f"      Install: npm install -g @anthropic-ai/claude-code")
        else:
            print(f"   ⚠️  Claude CLI failed: {e}")
    except Exception as e:
        print(f"   ⚠️  Claude CLI failed: {e}")

    # 2. Try Anthropic API (if API key available)
    print("   Checking Anthropic API...")
    anthropic_key = os.getenv('ANTHROPIC_API_KEY')
    if anthropic_key:
        try:
            lm = dspy.LM('anthropic/claude-3-5-haiku-20241022', api_key=anthropic_key)
            dspy.configure(lm=lm)
            print("   ✅ Configured with Anthropic Claude 3.5 Haiku\n")
            return True
        except Exception as e:
            print(f"   ⚠️  Anthropic API failed: {e}")
    else:
        print("   ⚠️  ANTHROPIC_API_KEY not set")

    # 3. Try OpenAI (if API key available)
    print("   Checking OpenAI API...")
    openai_key = os.getenv('OPENAI_API_KEY')
    if openai_key:
        try:
            lm = dspy.LM('openai/gpt-4o-mini', api_key=openai_key)
            dspy.configure(lm=lm)
            print("   ✅ Configured with OpenAI GPT-4o-mini\n")
            return True
        except Exception as e:
            print(f"   ⚠️  OpenAI API failed: {e}")
    else:
        print("   ⚠️  OPENAI_API_KEY not set")

    # 4. Try OpenRouter (if API key available)
    print("   Checking OpenRouter API...")
    openrouter_key = os.getenv('OPENROUTER_API_KEY')
    if openrouter_key:
        try:
            lm = dspy.LM('openrouter/meta-llama/llama-3.3-70b-instruct:free', api_key=openrouter_key)
            dspy.configure(lm=lm)
            print("   ✅ Configured with OpenRouter (free Llama model)\n")
            return True
        except Exception as e:
            print(f"   ⚠️  OpenRouter API failed: {e}")
    else:
        print("   ⚠️  OPENROUTER_API_KEY not set")

    # No LLM provider available
    print("\n❌ No LLM provider available")
    print("\n💡 To use Jotty's LLM generation:")
    print("   1. Install Claude CLI: npm install -g @anthropic-ai/claude-code")
    print("   2. Or set API key: export ANTHROPIC_API_KEY='your-key'")
    print("   3. Or set API key: export OPENAI_API_KEY='your-key'")
    print("   4. Or set API key: export OPENROUTER_API_KEY='your-key'\n")
    return False


def generate_guide_content(topic: str, goal: str):
    """Use Jotty to generate comprehensive guide content with DSPy"""

    print("\n" + "=" * 100)
    print(f"  JOTTY MULTI-AGENT SYSTEM: Generating '{topic} for Dummies'")
    print("=" * 100 + "\n")

    # Show what Jotty is configured to do
    print("📋 Jotty Agent Configuration:")
    print("   Agent Type: ComprehensiveGuideExpertSignature (DSPy ChainOfThought)")
    print(f"   Topic: {topic}")
    print(f"   Goal: {goal}")
    print("   Output Fields (17 sections):")
    print("      1. introduction - Engaging intro for beginners")
    print("      2. history - History and background")
    print("      3. fundamentals - Core concepts and types")
    print("      4. characteristics - Key features")
    print("      5. maintenance - Care and upkeep")
    print("      6. benefits - Advantages and positives")
    print("      7. skills - Required knowledge")
    print("      8. health_safety - Health and safety")
    print("      9. resources - Materials needed")
    print("     10. getting_started - How to begin")
    print("     11. best_practices - Tips and techniques")
    print("     12. common_issues - Challenges to avoid")
    print("     13. community - Social aspects")
    print("     14. environment - Situational factors")
    print("     15. selection - How to choose")
    print("     16. costs - Financial considerations")
    print("     17. conclusion - Summary and advice")
    print("\n")

    # Configure LLM
    llm_configured = configure_llm()

    if llm_configured:
        print(f"\n🤖 Initializing Comprehensive Guide Expert Agent with LLM...")

        try:
            # Use ChainOfThought for step-by-step reasoning
            guide_expert = dspy.ChainOfThought(ComprehensiveGuideExpertSignature)

            print("✅ Agent initialized\n")
            print(f"🔍 Generating comprehensive {topic} guide with LLM...")
            print("   (This may take 1-2 minutes - the LLM is generating 17 sections)\n")

            # Generate content
            result = guide_expert(
                topic=topic,
                goal=goal
            )

            print("✅ Content generated by LLM successfully!")
            print("   📊 All 17 sections generated by AI\n")
            return result, topic

        except Exception as e:
            print(f"❌ Error during LLM generation: {e}")
            import traceback
            traceback.print_exc()
            print("\n💡 Falling back to pre-written content\n")
            return create_fallback_content(), topic
    else:
        print("\n" + "="*100)
        print("  DEMONSTRATION MODE")
        print("="*100)
        print("\n📝 Jotty is configured to use the ComprehensiveGuideExpertSignature agent above.")
        print("   When an LLM is configured, it would:")
        print(f"   1. Receive topic: '{topic}' and goal: '{goal}'")
        print("   2. Use Chain-of-Thought reasoning to plan content")
        print("   3. Generate all 17 sections using the LLM")
        print("   4. Return structured output matching the signature")
        print("\n   Since no LLM is configured, using pre-written fallback content.")
        print("   (The fallback content is comprehensive but static)\n")
        return create_fallback_content(), topic


def create_fallback_content():
    """Fallback content if LLM is not configured"""

    class FallbackResult:
        def __init__(self):
            self.introduction = """
**Welcome to the World of Poodles!**

Poodles are one of the most beloved and recognizable dog breeds in the world. Despite their
reputation as "fancy" show dogs, poodles are actually incredibly versatile, intelligent, and
affectionate companions. Whether you're considering bringing a poodle into your home or you've
just welcomed one into your family, this guide will walk you through everything you need to
know about these remarkable dogs.

Poodles combine elegance with athleticism, intelligence with playfulness, and sophistication
with loyalty. They're not just beautiful to look at – they're deeply rewarding companions who
form strong bonds with their families.
"""

            self.history = """
**A Noble Heritage**

The poodle's history is as elegant as the breed itself. Despite their association with France
(where they became the national dog), poodles actually originated in Germany over 400 years ago.
The name "poodle" comes from the German word "Pudelhund," meaning "splash dog" or "water dog."

Originally, poodles were bred as water retrievers, helping hunters collect waterfowl from lakes
and rivers. Their distinctive clip wasn't just for show – it served a practical purpose. The
shaved areas reduced drag in water, while the pompoms protected vital joints and organs from
the cold.

In the 1700s, poodles made their way to France, where they became favorites of the aristocracy.
French nobility loved their intelligence and elegance, and the breed's association with French
culture became permanent. Today, the poodle remains one of the most popular breeds worldwide.
"""

            self.breed_types = """
**Three Sizes, Same Great Dog**

Poodles come in three distinct sizes, each with its own charm:

**Standard Poodle** (45-70 pounds, over 15 inches tall):
- The original size, bred for water retrieving
- Athletic and energetic
- Great for active families
- Excellent with children due to sturdy build
- Ideal for owners who want a larger companion

**Miniature Poodle** (15-17 pounds, 10-15 inches tall):
- Perfect "middle ground" size
- Equally intelligent and trainable
- Good for apartments with adequate exercise
- Adaptable to various living situations
- Less demanding than Standard but more robust than Toy

**Toy Poodle** (4-6 pounds, under 10 inches tall):
- Smallest variety
- Perfect lap dog
- Ideal for seniors or singles
- Can live comfortably in small spaces
- More delicate, requires gentle handling

**Important Note**: Regardless of size, all poodles share the same temperament, intelligence,
and grooming needs. Size should be chosen based on your living situation, activity level, and
personal preference – not because one size is "better" than another.
"""

            self.appearance = """
**A Distinctive Look**

Poodles are instantly recognizable by their unique appearance:

**Coat Characteristics**:
- Single-layer coat (no undercoat)
- Curly, dense, and water-resistant
- Hypoallergenic (minimal shedding)
- Comes in solid colors: white, black, apricot, cream, red, brown, silver, blue
- Grows continuously like human hair

**Body Type**:
- Square, athletic build
- Proud, elegant carriage
- Long, straight muzzle
- Dark, oval eyes with alert expression
- Hanging ears close to the head
- High-set tail, traditionally docked (though this varies by country)

**The Famous Clips**:
While poodles can be kept in various styles, the classic clips include:
- **Puppy Clip**: Simple, practical all-over cut
- **Continental Clip**: Traditional show cut with pompoms
- **English Saddle Clip**: Another show style
- **Sporting Clip**: Practical, short all-over cut

For pet owners, a simple "puppy clip" or "sporting clip" is most practical and easier to maintain.
"""

            self.grooming = """
**Grooming: A Commitment You Must Make**

Poodles are high-maintenance when it comes to grooming. This is NOT optional – it's an essential
part of responsible poodle ownership.

**Daily Care**:
- Brush daily to prevent matting (15-20 minutes)
- Check ears for moisture/debris
- Wipe around eyes to prevent tear staining
- Brush teeth regularly

**Every 4-6 Weeks**:
- Professional grooming (or DIY if skilled)
- Full bath and blow-dry
- Complete clip/trim
- Nail trimming
- Ear cleaning
- Anal gland expression if needed

**Tools You'll Need**:
- Slicker brush
- Metal comb
- Grooming scissors
- Electric clippers (if DIY grooming)
- Nail clippers or grinder
- Dog shampoo and conditioner
- Ear cleaning solution

**Professional Grooming Costs**: $50-$100 per session (varies by location and size)

**Time Investment**:
- Daily brushing: 15-20 minutes
- Professional grooming: Every 4-6 weeks
- Or DIY grooming: 2-3 hours every 4-6 weeks

**The Non-Negotiable Truth**: If you can't commit to this grooming schedule, a poodle is not
the right breed for you. Neglected coats become painfully matted, leading to skin infections
and requiring complete shave-downs.
"""

            self.temperament = """
**Personality: Smart, Loving, and Spirited**

Poodles are beloved for their wonderful temperament:

**Intelligence**:
- Ranked #2 in canine intelligence (after Border Collies)
- Learn new commands in fewer than 5 repetitions
- Excel at problem-solving
- Can be trained for complex tasks
- Remember routines and patterns

**Affection**:
- Form deep bonds with family members
- Devoted and loyal
- Love to be involved in family activities
- Can be "velcro dogs" – following you everywhere
- Thrive on human companionship

**Energy Level**:
- Moderate to high energy
- Playful and fun-loving
- Need both physical and mental stimulation
- Calm indoors when exercised properly
- Can adapt to owner's activity level to some degree

**Social Nature**:
- Generally friendly with proper socialization
- Can be reserved with strangers initially
- Usually good with other dogs
- May have prey drive toward small animals
- Need early socialization to prevent shyness

**Sensitivity**:
- Highly attuned to owner's emotions
- Respond poorly to harsh training methods
- Can develop separation anxiety if over-dependent
- Need consistent, gentle leadership
- May become anxious in chaotic environments

**Watchdog Qualities**:
- Alert and protective of their family
- Will bark to alert you to visitors
- Not aggressive, but vigilant
- Can be trained to minimize excessive barking
"""

            self.intelligence = """
**A Brilliant Mind in a Fluffy Package**

Poodles are exceptionally intelligent, which is both a blessing and a challenge:

**The Upside**:
- **Quick Learners**: Master basic obedience in weeks
- **Problem Solvers**: Can figure out puzzles and challenges
- **Versatile**: Excel in various dog sports (agility, obedience, tracking)
- **Trainable**: Can learn hundreds of commands and tricks
- **Adaptable**: Adjust well to different situations
- **Sensitive**: Understand tone, body language, and routines

**The Challenge**:
- **Too Smart**: May outsmart inexperienced owners
- **Boredom**: Need constant mental stimulation or become destructive
- **Stubborn**: If they don't see the point, they may refuse
- **Manipulative**: Learn to train YOU if not handled properly
- **Sensitive**: Poor training methods can create anxiety or fear

**Training Requirements**:
- **Consistency**: Same rules, every time, from everyone
- **Positive Reinforcement**: Rewards-based training works best
- **Mental Exercise**: Puzzle toys, training sessions, new tricks
- **Variety**: Keep training interesting – they get bored with repetition
- **Early Start**: Begin training from puppyhood

**Jobs Poodles Excel At**:
- Service dogs (medical alert, mobility assistance)
- Therapy dogs
- Search and rescue
- Truffle hunting (yes, really!)
- Dog sports competition
- Performing arts (circus, shows)

**Bottom Line**: A poodle's intelligence means they NEED a job. An under-stimulated poodle
is a destructive, anxious, or depressed poodle. Plan to invest 30-60 minutes daily in training,
play, and mental enrichment.
"""

            self.health_care = """
**Health: What Every Owner Should Know**

Poodles are generally healthy but have breed-specific concerns:

**Common Health Issues by Size**:

**Standard Poodles**:
- Hip dysplasia
- Bloat (gastric torsion) – LIFE-THREATENING EMERGENCY
- Addison's disease
- Sebaceous adenitis (skin condition)
- Average lifespan: 12-15 years

**Miniature & Toy Poodles**:
- Luxating patella (knee issues)
- Progressive retinal atrophy (eye disease)
- Epilepsy
- Legg-Calve-Perthes disease (hip disorder in Toys)
- Dental issues (especially Toys)
- Average lifespan: 12-15 years (Toys can live to 18+)

**Preventive Care**:
- Annual vet checkups (biannual for seniors)
- Keep vaccinations current
- Monthly heartworm prevention
- Flea and tick prevention
- Dental cleaning as recommended
- Healthy weight maintenance
- Regular exercise

**Health Testing for Breeders**:
Responsible breeders test for:
- Hip dysplasia (OFA or PennHIP)
- Eye diseases (CERF exam)
- von Willebrand's disease (bleeding disorder)
- Thyroid function
- Genetic disease panels

**Red Flags to Watch For**:
- Sudden lethargy or behavior changes
- Loss of appetite
- Vomiting or diarrhea lasting >24 hours
- Difficulty breathing
- Swollen, hard abdomen (bloat – EMERGENCY)
- Limping or difficulty walking
- Excessive scratching or skin changes

**Healthcare Costs** (Annual):
- Routine care: $500-$800
- Emergency fund: $1,000-$3,000
- Consider pet insurance for peace of mind
"""

            self.nutrition = """
**Feeding Your Poodle: Nutrition Fundamentals**

Proper nutrition is essential for your poodle's health:

**Basic Guidelines**:

**Amount to Feed** (varies by size and activity level):
- **Toy**: 1/4 - 1/2 cup daily, divided into 2-3 meals
- **Miniature**: 3/4 - 1 cup daily, divided into 2 meals
- **Standard**: 1.5 - 3 cups daily, divided into 2 meals

**Choosing Quality Food**:
- High-quality protein as first ingredient
- Balanced omega-3 and omega-6 fatty acids
- No fillers, by-products, or artificial colors
- AAFCO-approved for life stage
- Consider grain-free if allergies present

**Life Stage Nutrition**:
- **Puppies** (0-12 months): Puppy formula, 3-4 meals daily
- **Adults** (1-7 years): Adult maintenance formula, 2 meals daily
- **Seniors** (7+ years): Senior formula, 2 meals daily, lower calories

**Special Considerations**:
- **Standards**: Risk of bloat – avoid exercise before/after meals
- **Toys**: Small kibble size, prone to hypoglycemia (need frequent meals)
- **Active dogs**: May need performance formula
- **Overweight dogs**: Weight management formula

**Foods to AVOID**:
- Chocolate (toxic)
- Grapes and raisins (kidney failure)
- Onions and garlic (toxic)
- Xylitol (artificial sweetener – deadly)
- Macadamia nuts
- Avocado
- Alcohol
- Bones that can splinter (cooked chicken bones)

**Treats**:
- Should be <10% of daily calories
- Use for training rewards
- Choose healthy options (carrots, green beans, small training treats)

**Water**:
- Fresh, clean water available at ALL times
- Wash bowl daily
- Monitor intake (sudden increases can indicate health issues)
"""

            self.exercise = """
**Exercise: Keeping Your Poodle Physically Fit**

Poodles are energetic dogs that need regular exercise:

**Daily Exercise Requirements**:

**Standard Poodles**:
- 60-90 minutes of exercise daily
- Long walks, jogging, swimming
- Vigorous play sessions
- Dog sports (agility, dock diving)

**Miniature Poodles**:
- 45-60 minutes of exercise daily
- Moderate walks
- Fetch games
- Interactive play

**Toy Poodles**:
- 30-45 minutes of exercise daily
- Short walks
- Indoor play
- Gentle activities

**Ideal Activities**:
- **Swimming**: Natural water retrievers, excellent exercise
- **Fetch**: Satisfies retrieving instincts
- **Agility Courses**: Mental + physical stimulation
- **Hiking**: Standards love outdoor adventures
- **Interactive Toys**: Flirt poles, tug toys
- **Dog Parks**: Socialization + exercise (supervise carefully)

**Mental Exercise is EQUALLY Important**:
- Training sessions (10-15 minutes, 2-3x daily)
- Puzzle toys and food dispensers
- Hide-and-seek games
- Learning new tricks
- Scent work activities

**Exercise by Life Stage**:
- **Puppies**: Short, frequent play sessions; avoid over-exercise (growth plates)
- **Adults**: Full exercise regimen
- **Seniors**: Gentle walks, swimming, adapted activities

**Signs of Insufficient Exercise**:
- Destructive behavior (chewing, digging)
- Excessive barking
- Hyperactivity
- Attention-seeking behaviors
- Weight gain
- Anxiety or depression

**Weather Considerations**:
- **Hot Weather**: Early morning/evening walks, avoid overheating
- **Cold Weather**: Poodles get cold easily; consider sweaters/coats
- **Rain**: Water-resistant coat, but still may resist getting wet
"""

            self.training_basics = """
**Training Your Poodle: Setting Up for Success**

Poodles are highly trainable, but they require the right approach:

**Start Early**:
- Begin training at 8 weeks old
- Puppies are like sponges – they learn fast
- Early experiences shape adult behavior
- Positive first experiences are crucial

**Training Principles**:

1. **Positive Reinforcement**:
   - Reward desired behaviors immediately
   - Use treats, praise, toys
   - NEVER use punishment or harsh corrections
   - Poodles are sensitive – positive methods work best

2. **Consistency**:
   - Same commands from all family members
   - Same rules, every time
   - Don't allow behaviors you'll later prohibit
   - 5-10 minute sessions, multiple times daily

3. **Patience**:
   - Some lessons take time
   - Regression is normal
   - Stay calm and positive
   - End on a positive note

**Essential Commands**:
- **Sit**: Foundation for impulse control
- **Stay**: Safety and impulse control
- **Come**: Critical for safety
- **Down**: Relaxation and control
- **Leave It**: Prevents eating dangerous items
- **Drop It**: Safety when they grab something
- **Heel/Walk Nice**: Pleasant walks

**House Training**:
- Take outside every 2 hours (puppies)
- After meals, naps, play
- Praise immediately when they go outside
- Never punish accidents
- Crate training accelerates the process
- Most poodles house-train easily (they're clean by nature)

**Crate Training**:
- Positive association (treats, toys, meals in crate)
- Never use as punishment
- Appropriate size (stand, turn, lie down)
- Use for house training and safe space
- Don't overuse – not a babysitter

**Common Behavioral Issues**:
- **Barking**: Identify triggers, teach "quiet" command
- **Jumping**: Ignore until four paws on floor, then reward
- **Separation Anxiety**: Gradual alone time, crate training
- **Resource Guarding**: Professional trainer recommended
- **Fear/Shyness**: Gradual exposure, positive associations

**When to Seek Professional Help**:
- Aggression of any kind
- Severe anxiety or fear
- Resource guarding
- Persistent unwanted behaviors
- If you're frustrated or overwhelmed

**Training Classes**:
- Puppy kindergarten (8-16 weeks)
- Basic obedience (all ages)
- Advanced training (tricks, sports)
- Provides socialization opportunity
"""

            self.socialization = """
**Socialization: Creating a Confident, Friendly Poodle**

Proper socialization is critical for poodles:

**Critical Period**: 3-14 weeks of age
- Most important socialization window
- Positive experiences during this time shape adult temperament
- Missing this window makes socialization harder (but not impossible)

**What to Socialize To**:

**People**:
- Men, women, children
- Different ages, sizes, ethnicities
- People with hats, glasses, beards
- People in uniforms
- People using mobility aids

**Environments**:
- Different surfaces (grass, concrete, gravel, metal grates)
- Urban settings (crowds, traffic noise)
- Rural settings
- Vet clinic (make positive visits)
- Groomer (essential for poodles)
- Car rides
- Stairs, elevators

**Other Animals**:
- Friendly dogs (various sizes and breeds)
- Cats (if you have them)
- Other pets in your household
- Wildlife (from a safe distance)

**Sounds**:
- Vacuum cleaners
- Lawn mowers
- Thunder/fireworks recordings (start quiet, gradually louder)
- Children playing/screaming
- Traffic noise
- Doorbells

**Experiences**:
- Handling (paws, ears, mouth, tail)
- Grooming tools (brushes, clippers)
- Wearing collar/harness
- Bathing
- Nail trimming
- Being alone briefly

**How to Socialize Properly**:

1. **Go Slow**:
   - Don't overwhelm
   - Watch for stress signals
   - Let puppy set the pace

2. **Keep it Positive**:
   - Pair new experiences with treats
   - Stay calm and happy yourself
   - Never force interactions
   - End on a good note

3. **Safety First**:
   - Until fully vaccinated, avoid dog parks and unknown dogs
   - Carry small puppies in risky areas
   - Puppy classes with vaccination requirements are safe
   - Invite vaccinated, friendly dogs to your home

4. **Watch Body Language**:
   - **Confident**: Relaxed body, wagging tail, curious
   - **Stressed**: Tucked tail, ears back, trying to escape
   - **Fearful**: Cowering, shaking, hiding
   - If stressed, create more distance and go slower

**Ongoing Socialization**:
- Continue throughout adolescence (up to 2 years)
- Regular exposure to different environments
- Positive experiences with new people and dogs
- Don't stop after puppyhood

**Red Flags**:
- Extreme fear that doesn't improve
- Aggression toward people or dogs
- Inability to calm down in new situations
- Seek professional help immediately
"""

            self.family_compatibility = """
**Poodles and Families: A Great Match**

Poodles can make wonderful family dogs when properly matched:

**With Children**:

**Standard Poodles**:
- ✅ Excellent with kids (sturdier build)
- ✅ Playful and energetic for active families
- ✅ Patient with gentle, respectful children
- ⚠️ Teach children to respect dog's space
- ⚠️ Supervise toddlers (any dog can be overwhelmed)

**Miniature Poodles**:
- ✅ Good with school-age children
- ⚠️ May be too delicate for rough toddlers
- ⚠️ Can be snappy if mishandled
- ✅ Great playmate for gentle kids

**Toy Poodles**:
- ⚠️ NOT recommended for young children
- Too small and delicate
- Can be injured by rough play
- May become defensive/snappy if scared
- ✅ Excellent with gentle older children (10+)

**Teaching Children**:
- Gentle petting only
- No pulling ears, tail, fur
- Leave dog alone when eating
- Respect crate as dog's safe space
- No riding, sitting on, or climbing on dog
- Recognize when dog wants space

**With Other Pets**:

**Other Dogs**:
- Generally good with proper socialization
- May prefer similar-sized dogs
- Introduce gradually and properly
- Same-sex aggression can occur
- Multiple poodles often do well together

**Cats**:
- Can live peacefully with cats
- Best when raised together
- Some have prey drive toward running cats
- Supervise initial interactions
- Provide cat with escape routes

**Small Pets** (rabbits, hamsters, birds):
- Water retriever heritage = prey drive
- Supervision essential
- Never leave unsupervised
- Some poodles can never be trusted around small pets

**Lifestyle Compatibility**:

**Best For**:
- Active individuals or families
- People who enjoy grooming/can afford grooming
- Those wanting an intelligent, trainable dog
- Homes with time for daily exercise and training
- People with allergies (low-shedding)

**Not Ideal For**:
- People wanting low-maintenance dogs
- Those unable to afford grooming
- Very sedentary lifestyles
- People away from home 10+ hours daily
- Those who don't enjoy training/interaction

**Age Considerations**:
- **Singles/Couples**: Any size works
- **Families with kids**: Standard or Miniature preferred
- **Seniors**: Toy or Miniature (easier to handle)
- **Active young adults**: Standard (hiking/jogging partner)
"""

            self.living_conditions = """
**Housing: Where Poodles Thrive**

Poodles are adaptable but have specific needs:

**Apartment Living**:

**Toy & Miniature**:
- ✅ Excellent apartment dogs
- ✅ Don't need yard (but appreciate it)
- ⚠️ MUST get daily walks/exercise
- ⚠️ Can bark – train early
- ✅ Compact size easy to manage

**Standard**:
- ⚠️ Possible but challenging in small apartments
- Need significant daily exercise
- Require more space to move comfortably
- Better suited to larger apartments
- Access to dog parks essential

**House with Yard**:
- ✅ Ideal for all sizes
- ✅ Standards especially appreciate yard
- ⚠️ Fence required (poodles will roam)
- ⚠️ Yard is NOT a substitute for walks/interaction
- ⚠️ Don't leave outside unsupervised long periods

**Climate Considerations**:

**Hot Climates**:
- ✅ Tolerate heat better than cold
- Keep groomed shorter in summer
- Provide shade and water
- Avoid exercise during peak heat
- Watch for overheating (brachycephalic breeds more at risk, but still monitor)

**Cold Climates**:
- ❄️ Get cold easily (single coat, low body fat)
- Need sweaters/coats in winter
- Booties for ice/salt protection
- Shorten outdoor time in extreme cold
- Keep coat slightly longer for warmth

**Indoor vs. Outdoor**:
- **Indoor Dogs**: Poodles should live INDOORS with family
- **Not Outdoor Dogs**: Single coat, need climate control
- **Family-Oriented**: Need interaction, not isolation
- **Safe Yard Time**: Supervised outdoor play is great
- **Never Chained**: Inhumane and dangerous

**Space Requirements**:
- Less about space, more about exercise
- Small apartment + 90 minutes daily exercise > large yard + neglect
- Mental stimulation matters more than square footage
- Access to safe outdoor areas for exercise essential

**Urban vs. Rural**:

**Urban**:
- ✅ Poodles adapt well to city life
- ✅ Enjoy walks in busy environments (when socialized)
- ⚠️ Noise sensitivity – socialize to city sounds
- ✅ Great café companions
- ⚠️ Limited off-leash areas – need alternatives

**Rural**:
- ✅ Plenty of exercise opportunities
- ✅ Natural environment stimulation
- ⚠️ Predators (coyotes, eagles for Toys)
- ⚠️ More parasites (ticks, fleas)
- ⚠️ Less socialization – make effort to expose to people/dogs

**The Bottom Line**: Poodles are adaptable, but they need:
- Climate-controlled indoor living
- Daily exercise (regardless of yard)
- Mental stimulation
- Family interaction
- Safe, secure environment
"""

            self.choosing_poodle = """
**Choosing Your Poodle: Making the Right Decision**

Finding the right poodle requires research and patience:

**Breeder vs. Rescue**:

**Reputable Breeder**:
- ✅ Predictable temperament and health
- ✅ Health testing of parents
- ✅ Early socialization
- ✅ Breeder support throughout dog's life
- ✅ Can choose size, color
- ❌ Expensive ($1,500-$3,000+)
- ❌ Waiting lists

**Finding a Reputable Breeder**:
- Health tests parents (hips, eyes, genetics)
- Raises puppies in home environment
- Allows you to meet parent dogs
- Asks YOU questions (screening homes)
- Provides health guarantee
- Doesn't always have puppies available
- Member of breed club
- References from previous buyers

**Red Flags**:
- ❌ Always has puppies available
- ❌ Won't let you visit
- ❌ No health testing
- ❌ Sells puppies before 8 weeks
- ❌ Multiple breeds available
- ❌ Ships puppies sight unseen
- ❌ "Designer breeds" (doodles, etc.)
- ❌ Meets in parking lots

**Rescue/Adoption**:
- ✅ Save a life
- ✅ Lower cost ($200-$500)
- ✅ Adult dogs (known temperament)
- ✅ Often already trained
- ⚠️ Unknown history possible
- ⚠️ May have behavioral issues
- ⚠️ Health history unknown

**Poodle-Specific Rescues**:
- Specialize in breed
- Foster homes assess temperament
- Help match right dog to right home
- Post-adoption support

**Choosing Size**:
- **Toy**: Seniors, singles, small spaces, gentle handling
- **Miniature**: Families with older kids, apartments, versatile
- **Standard**: Active families, houses, want larger dog, kids

**Male vs. Female**:
- More individual than gender-based
- Males: Often more affectionate, slightly larger
- Females: Sometimes more independent, smaller
- Spay/neuter reduces gender-related behaviors

**Puppy vs. Adult**:

**Puppy** (8 weeks - 1 year):
- ✅ Bond from start
- ✅ Train to your preferences
- ✅ See them grow
- ❌ House training required
- ❌ Destructive puppy phase
- ❌ More time-intensive

**Adult** (1+ years):
- ✅ Known temperament
- ✅ Often already trained
- ✅ Past destructive puppy stage
- ✅ May be calmer
- ⚠️ May have learned bad habits
- ⚠️ Adjustment period needed

**Health Check Before Bringing Home**:
- Vet exam within 72 hours
- Review health records
- Discuss vaccination schedule
- Check for parasites
- Establish care plan

**Questions to Ask**:
- Health testing done on parents?
- Can I meet parent dogs?
- What health issues in breed/lines?
- What's included (vaccinations, microchip, contract)?
- What support do you provide after purchase?
- Can I return if it doesn't work out?
- References from previous buyers?

**Trust Your Instincts**:
- If something feels wrong, walk away
- Reputable sources won't pressure you
- Take time to decide
- Visit multiple times if possible
"""

            self.costs = """
**The Real Cost of Poodle Ownership**

Poodles are NOT cheap dogs to own. Here's the honest financial breakdown:

**Initial Costs** (First Year):

**Purchase/Adoption**:
- Reputable Breeder: $1,500 - $3,000+ (Standards often more)
- Rescue/Shelter: $200 - $500
- "Bargain" breeders: NOT recommended (health issues cost more later)

**Initial Supplies** ($500-$800):
- Crate: $50-$150
- Bed: $30-$100
- Food/water bowls: $20-$40
- Collar, leash, harness: $40-$80
- ID tag + microchip: $50-$80
- Toys: $50-$100
- Grooming supplies: $100-$200
- Gates/exercise pen: $50-$150
- Puppy training pads: $30-$50

**First Year Veterinary** ($500-$1,000):
- Initial exam: $50-$100
- Vaccinations (series): $150-$300
- Spay/Neuter: $200-$500
- Microchip: $25-$50 (if not included)
- Heartworm/flea prevention: $150-$300
- Puppy wellness visits: $100-$200

**First Year Total**: $3,000 - $5,500+

**Annual Costs** (After First Year):

**Grooming** ($600-$1,200/year):
- Professional grooming every 6 weeks: $50-$100 per session
- 8-9 sessions per year
- DIY grooming: Equipment ($200-$500 one-time), time investment

**Food** ($300-$600/year):
- Toy: $200-$300/year
- Miniature: $300-$400/year
- Standard: $400-$600/year
- Quality matters – cheap food = health problems

**Routine Veterinary** ($300-$600/year):
- Annual exam: $50-$100
- Vaccinations: $80-$150
- Heartworm test: $30-$50
- Flea/tick/heartworm prevention: $200-$350
- Dental cleaning (every 1-2 years): $300-$800

**Other Expenses**:
- Toys/replacements: $100-$200/year
- Treats: $100-$150/year
- Training classes: $100-$300 (first year)
- Boarding/pet sitting: $25-$75/day
- Pet insurance: $30-$60/month ($360-$720/year)

**Annual Total**: $1,500 - $3,500

**15-Year Lifetime Cost**: $25,000 - $50,000+

**Emergency Fund**: Keep $2,000-$5,000 for unexpected veterinary emergencies

**Money-Saving Tips**:
- Learn to groom yourself (saves $600-$1,200/year)
- Buy quality food (prevents health issues)
- Pet insurance (if you can't afford $5,000 emergency)
- Preventive care (cheaper than treating illness)
- Training prevents behavioral problems

**Can You Afford a Poodle?**

Ask yourself:
- Can I afford $200-$300 monthly expenses?
- Do I have $2,000-$5,000 emergency fund?
- Can I commit for 12-15+ years?
- Will I skip grooming to save money? (Don't get a poodle!)
- Can I afford quality food and vet care?

**If money is tight**, consider:
- Smaller size (lower food/some vet costs)
- Pet insurance
- Learn to groom
- Adult rescue (lower initial costs)

**The Bottom Line**: Poodles are wonderful, but expensive. If you can't commit financially,
consider a lower-maintenance breed. Your poodle deserves proper care, and cutting corners
leads to suffering (matted coats, poor health, behavioral issues).
"""

            self.conclusion = """
**Final Thoughts: Is a Poodle Right for You?**

Congratulations on making it through this comprehensive guide! By now, you should have a clear
picture of what poodle ownership truly involves.

**Poodles Are Perfect For You If**:
- ✅ You want an intelligent, trainable companion
- ✅ You have time for daily exercise and mental stimulation
- ✅ You can commit to grooming (or afford professional grooming)
- ✅ You want a low-shedding dog (allergies)
- ✅ You enjoy active involvement with your dog
- ✅ You have patience for training
- ✅ You can afford quality care
- ✅ You want a loyal, affectionate family member

**Poodles Are NOT Right For You If**:
- ❌ You want a low-maintenance dog
- ❌ You're away from home 10+ hours daily
- ❌ You can't afford regular professional grooming
- ❌ You want an "outdoor dog"
- ❌ You prefer sedentary lifestyle
- ❌ You don't enjoy training/mental stimulation
- ❌ You want a "guard dog" (they're alert, not aggressive)

**The Poodle Promise**:

When you bring a poodle into your life, you're not just getting a pet – you're gaining:
- A brilliant companion who will constantly amaze you
- A loyal friend who bonds deeply with you
- An elegant athlete who loves to play
- A clownish entertainer who makes you laugh
- A sensitive soul who understands your moods
- A devoted family member for 12-15+ years

**In Return, Your Poodle Needs**:
- Daily grooming and professional care every 6 weeks
- 30-90 minutes of exercise (size-dependent)
- Mental stimulation and training
- Quality nutrition and veterinary care
- Love, patience, and respect
- A lifetime commitment

**Getting Started**:

1. **Research More**: Join poodle forums, talk to owners, visit breeders/rescues
2. **Prepare Your Home**: Puppy-proof, buy supplies
3. **Find Reputable Source**: Breeder or rescue
4. **Build Your Team**: Find vet, groomer, trainer
5. **Commit Fully**: This is a 12-15+ year responsibility

**Remember**: The decision to bring any dog into your home should never be impulsive.
Poodles are extraordinary dogs, but they're not for everyone. Be honest about your lifestyle,
resources, and commitment level.

**A poodle isn't just a pet – they're a lifestyle choice.**

If you can meet their needs, a poodle will reward you with unwavering loyalty, endless
entertainment, and a love that lasts a lifetime. They're not called "the perfect companion"
for nothing.

**Welcome to the wonderful world of poodles! May your journey together be filled with joy,
love, and only occasionally with mud after they've discovered a puddle (they never lose their
"pudel" instincts!)**

---

*For more information, consult your veterinarian, a professional dog trainer, or join a
poodle breed club in your area. Always prioritize your dog's health and well-being.*
"""

    return FallbackResult()


def create_document_from_result(result, topic: str):
    """Convert generated content to Document object"""

    print("📄 Creating structured document...\n")

    doc = Document(
        title=f"{topic} for Dummies: A Comprehensive Guide",
        author="Jotty AI Research Team",
        topic=topic,
        source_type="jotty-multi-agent"
    )

    # Generic section mapping
    sections = [
        (result.introduction, "Introduction"),
        (result.history, "History & Background"),
        (result.fundamentals, "Fundamentals"),
        (result.characteristics, "Key Characteristics"),
        (result.maintenance, "Maintenance & Care"),
        (result.benefits, "Benefits & Advantages"),
        (result.skills, "Required Skills & Knowledge"),
        (result.health_safety, "Health & Safety"),
        (result.resources, "Resources & Materials"),
        (result.getting_started, "Getting Started"),
        (result.best_practices, "Best Practices"),
        (result.common_issues, "Common Issues & Challenges"),
        (result.community, "Community & Social Aspects"),
        (result.environment, "Environmental Considerations"),
        (result.selection, "Selection & Decision Making"),
        (result.costs, "Financial Considerations"),
        (result.conclusion, "Conclusion"),
    ]

    # Add all sections
    for content, title in sections:
        doc.add_section(SectionType.TEXT, content, title=title)

    print(f"✅ Document created with {len(doc.sections)} sections")
    print(f"   Total content: {len(doc.full_content):,} characters\n")

    return doc


def generate_outputs(doc, topic: str):
    """Generate all output formats"""

    print("=" * 100)
    print("  GENERATING OUTPUT FILES")
    print("=" * 100 + "\n")

    # Create output directory (sanitize topic for directory name)
    topic_slug = topic.lower().replace(" ", "_").replace("/", "_")
    output_dir = Path(f"./outputs/{topic_slug}_guide")
    output_dir.mkdir(parents=True, exist_ok=True)

    generators = ContentGenerators()

    # Generate PDF (main request)
    print("📕 Generating PDF...")
    try:
        pdf_path = generators.generate_pdf(doc, output_path=output_dir, format='a4')
        print(f"✅ PDF: {pdf_path.name}")
        print(f"   Size: {pdf_path.stat().st_size:,} bytes ({pdf_path.stat().st_size/1024:.1f} KB)\n")
    except Exception as e:
        print(f"❌ PDF generation failed: {e}\n")
        return False, None

    # Also generate other formats
    print("📄 Generating Markdown...")
    try:
        md_path = generators.export_markdown(doc, output_path=output_dir)
        print(f"✅ Markdown: {md_path.name}\n")
    except Exception as e:
        print(f"⚠️  Markdown skipped: {e}\n")

    print("🌐 Generating HTML...")
    try:
        html_path = generators.generate_html(doc, output_path=output_dir)
        print(f"✅ HTML: {html_path.name}\n")
    except Exception as e:
        print(f"⚠️  HTML skipped: {e}\n")

    print("=" * 100)
    print("  SUCCESS!")
    print("=" * 100 + "\n")

    print(f"📁 Output Directory: {output_dir}")
    print(f"📚 Generated Files:\n")

    for file in sorted(output_dir.glob("*")):
        size = file.stat().st_size / 1024
        print(f"   - {file.name} ({size:.1f} KB)")

    print(f"\n🎯 Main PDF: {pdf_path}")
    print(f"\n✨ Your comprehensive '{topic} for Dummies' guide is ready!\n")

    return True, pdf_path


def main():
    """Main execution"""
    import argparse

    # Parse command-line arguments
    parser = argparse.ArgumentParser(
        description="Generate comprehensive beginner's guides using Jotty AI"
    )
    parser.add_argument(
        '--topic',
        type=str,
        default='Poodles',
        help='Topic to generate guide about (default: Poodles). Examples: "Python Programming", "Home Gardening", "Chess"'
    )
    parser.add_argument(
        '--goal',
        type=str,
        default=None,
        help='Specific goal or focus for the guide (optional)'
    )
    args = parser.parse_args()

    # Set default goal if not provided
    if args.goal is None:
        args.goal = f"Create a comprehensive, beginner-friendly guide to {args.topic} covering all essential topics"

    # Step 1: Generate content using Jotty
    result, topic = generate_guide_content(args.topic, args.goal)

    # Step 2: Create structured document
    doc = create_document_from_result(result, topic)

    # Step 3: Generate outputs (PDF and others)
    success, pdf_path = generate_outputs(doc, topic)

    if success:
        print(f"🎉 Mission accomplished! Jotty has created your {topic} guide.\n")
        return 0
    else:
        print("❌ PDF generation failed. Please check errors above.\n")
        return 1


if __name__ == "__main__":
    sys.exit(main())
