"""
V2V Trending Search Skill

Search for trending topics on V2V.ai and generate reports.
"""
import asyncio
import logging
from typing import Dict, Any
from datetime import datetime

logger = logging.getLogger(__name__)


async def search_v2v_trending_tool(params: Dict[str, Any]) -> Dict[str, Any]:
    """
    Search for trending topics on V2V.ai.
    
    Args:
        params: Dictionary containing:
            - query (str, optional): Search query (default: searches for trending)
            - format (str, optional): Output format - 'markdown', 'json' (default: 'markdown')
            - max_results (int, optional): Maximum results (default: 10)
    
    Returns:
        Dictionary with:
            - success (bool): Whether search succeeded
            - content (str): Search results in markdown format
            - results (list, optional): Raw results if format='json'
            - error (str, optional): Error message if failed
    """
    try:
        from core.registry.skills_registry import get_skills_registry
        
        query = params.get('query', 'trending topics')
        output_format = params.get('format', 'markdown')
        max_results = params.get('max_results', 10)
        
        logger.info(f"Searching V2V.ai for: {query}")
        
        # Use web-search skill to search V2V.ai
        registry = get_skills_registry()
        registry.init()
        
        web_search_skill = registry.get_skill('web-search')
        if not web_search_skill:
            return {
                'success': False,
                'error': 'web-search skill not available'
            }
        
        search_tool = web_search_skill.tools.get('search_web_tool')
        if not search_tool:
            return {
                'success': False,
                'error': 'search_web_tool not found'
            }
        
        # Search V2V.ai
        search_query = f"site:v2v.ai {query}" if query != 'trending topics' else "site:v2v.ai trending"
        
        search_result = await search_tool({
            'query': search_query,
            'max_results': max_results
        })
        
        if not search_result.get('success'):
            return {
                'success': False,
                'error': f"Search failed: {search_result.get('error')}"
            }
        
        results = search_result.get('results', [])
        
        if output_format == 'json':
            return {
                'success': True,
                'results': results,
                'count': len(results)
            }
        
        # Format as markdown
        markdown_content = f"# V2V.ai Trending Search Results\n\n"
        markdown_content += f"**Query:** {query}\n"
        markdown_content += f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        markdown_content += f"**Results:** {len(results)}\n\n"
        markdown_content += "---\n\n"
        
        for i, result in enumerate(results, 1):
            title = result.get('title', 'No title')
            url = result.get('url', '')
            snippet = result.get('snippet', result.get('description', 'No description'))
            
            markdown_content += f"## {i}. {title}\n\n"
            markdown_content += f"**URL:** {url}\n\n"
            markdown_content += f"{snippet}\n\n"
            markdown_content += "---\n\n"
        
        markdown_content += f"\n*Generated by Jotty V2V Trending Search Skill*\n"
        
        return {
            'success': True,
            'content': markdown_content,
            'results_count': len(results),
            'query': query
        }
        
    except Exception as e:
        logger.error(f"V2V search error: {e}", exc_info=True)
        return {
            'success': False,
            'error': f'V2V search failed: {str(e)}'
        }


__all__ = ['search_v2v_trending_tool']
