#!/usr/bin/env python3
"""
Generate a super-detailed PDF of Jotty's Learning System with full math.
Covers: TD-Lambda, Q-Learning, Thompson Sampling, Credit Assignment,
Swarm Coordination, Agent Learning, Stigmergy, Adaptive Components.
"""
import asyncio
import os
import sys
import time
from datetime import datetime
from pathlib import Path

JOTTY_ROOT = Path("/var/www/sites/personal/stock_market/Jotty")
sys.path.insert(0, str(JOTTY_ROOT))
from dotenv import load_dotenv
load_dotenv(JOTTY_ROOT / ".env")


MARKDOWN = r"""# Jotty Learning System — Complete Mathematical Deep Dive

**Generated:** {date}
**Scope:** Every learning component, every formula, every algorithm
**Generated by:** Jotty codebase analysis + agent research

---

## Table of Contents

1. System Overview & Learning Architecture
2. TD(λ) — Temporal Difference Learning with Eligibility Traces
3. Q-Learning with Natural Language States
4. Thompson Sampling — Bayesian Strategy Selection
5. Shaped Rewards — Dense Intermediate Signals
6. Credit Assignment — Shapley Values & Counterfactual Analysis
7. HRPO Group-Relative Baselines
8. Adaptive Learning Rate
9. Multi-Agent Swarm Learning Lifecycle
10. Team Coordination Patterns & Learning Signals
11. Stigmergy — Emergent Pheromone-Based Routing
12. MorphAgent Scoring (RCS/RDS/TRAS)
13. Agent Execution Pipeline & Learning Integration
14. Transfer Learning Across Domains
15. Convergence Properties & Plateau Detection
16. Episode Data Model & Storage
17. Complete Learning Loop — End to End

---

## 1. System Overview & Learning Architecture

Jotty implements a **hierarchical reinforcement learning architecture** where learning occurs at three levels simultaneously:

**Level 1 — Agent Level:** Each agent maintains its own TD-Lambda value function and eligibility traces. When an agent accesses a memory during execution, the trace for that memory increases. At episode end, all traced memories receive TD updates proportional to their eligibility.

**Level 2 — Swarm Level:** Swarms track coordination pattern effectiveness (pipeline vs parallel vs debate), paradigm success rates, and agent role assignments. Thompson Sampling over Beta distributions selects optimal configurations.

**Level 3 — Orchestrator Level:** The LearningService singleton aggregates episodes across all agents and swarms, maintains domain-specific value estimates, and provides retrieval-augmented context injection.

### Architecture Diagram

```
┌─────────────────────────────────────────────────────────────────┐
│                    ORCHESTRATOR LEVEL                            │
│  LearningService (singleton)                                    │
│  ├── EpisodeStore: persistent episode storage                   │
│  ├── ValueStore: state-action value estimates                   │
│  ├── Thompson Sampling: Beta(α,β) per arm                      │
│  ├── Domain Classification: task → domain routing               │
│  └── Context Injection: adaptive gates (>90% = no injection)    │
├─────────────────────────────────────────────────────────────────┤
│                      SWARM LEVEL                                │
│  SwarmLearningMixin                                             │
│  ├── _pre_execute_learning(): load context, warm up agents      │
│  ├── _post_execute_learning(): evaluate, credit assign, store   │
│  ├── MorphAgent Scorer: RCS/RDS/TRAS per agent                 │
│  ├── Stigmergy: pheromone deposit/sense/decay                  │
│  └── Coordination: 8 patterns affecting reward signals          │
├─────────────────────────────────────────────────────────────────┤
│                      AGENT LEVEL                                │
│  AgentRunner + TDLambdaLearner                                  │
│  ├── Memory retrieval → record_access() → eligibility trace     │
│  ├── Shaped rewards: architect +0.05, tool +0.10, goal +0.50   │
│  ├── Episode end: TD(λ) updates across all traced memories     │
│  ├── Q-Learning: NL state-action pairs with PER                │
│  └── Transfer Learning: cross-domain pattern reuse             │
└─────────────────────────────────────────────────────────────────┘
```

### Key Files

| Component | File | Lines |
|-----------|------|-------|
| TD-Lambda | `core/intelligence/learning/td_lambda.py` | ~900 |
| Q-Learning | `core/intelligence/learning/q_learning.py` | ~800 |
| Learning Service | `core/intelligence/learning/learning_service.py` | ~2400 |
| Learning Store | `core/intelligence/learning/learning_store.py` | ~400 |
| Shaped Rewards | `core/intelligence/learning/shaped_rewards.py` | ~300 |
| Algorithmic Credit | `core/intelligence/learning/algorithmic_credit.py` | ~500 |
| Reasoning Credit | `core/intelligence/learning/reasoning_credit.py` | ~400 |
| Adaptive Components | `core/intelligence/learning/adaptive_components.py` | ~350 |
| Swarm Learning Mixin | `core/intelligence/orchestration/swarms/_base/_learning_mixin.py` | ~650 |
| Swarm Learning Pipeline | `core/intelligence/orchestration/learning/swarm_learning_pipeline.py` | ~1800 |
| Team Coordinator | `core/intelligence/orchestration/swarms/base/team_coordinator.py` | ~1100 |
| Credit Assignment | `core/intelligence/orchestration/learning/credit_assignment.py` | ~400 |
| MAS Learning | `core/intelligence/orchestration/learning/mas_learning.py` | ~700 |
| Stigmergy | `core/intelligence/orchestration/learning/stigmergy.py` | ~150 |
| Agent Runner | `core/intelligence/orchestration/execution/agent_runner.py` | ~1850 |
| Swarm Manager | `core/intelligence/orchestration/core/swarm_manager.py` | ~3200 |

---

## 2. TD(λ) — Temporal Difference Learning with Eligibility Traces

### 2.1 Core Theory

TD(λ) combines the bootstrapping of TD(0) with the multi-step returns of Monte Carlo methods. The parameter λ ∈ [0,1] interpolates between them:

- **λ = 0**: Pure TD(0) — updates based only on immediate successor
- **λ = 1**: Monte Carlo — full episode return
- **λ = 0.95** (Jotty default): Heavily weights recent experience while still propagating long-term returns

### 2.2 Mathematical Formulation

**TD Error (δ):**

```
Terminal state:    δ_t = R_t - V(s_t)
Non-terminal:      δ_t = R_t + γ·V(s_{t+1}) - V(s_t)
```

**Eligibility Trace (accumulating):**

```
e_t(s) = γλ · e_{t-1}(s) + 𝟙[s_t = s]

where:
  γ = 0.99    (discount factor)
  λ = 0.95    (trace decay)
  𝟙[s_t = s]  = 1 if state s is visited at time t, else 0
```

**Value Update:**

```
V(s) ← V(s) + α · δ_t · e_t(s)

where:
  α = adaptive learning rate ∈ [0.001, 0.5]
```

### 2.3 Jotty Implementation

**Class: `TDLambdaLearner`**

```
Constructor:
  gamma         = 0.99     # Future rewards worth 99% of present
  lambda_trace  = 0.95     # Trace decay — recent states get 95% weight
  alpha         = adaptive  # See Section 8

State:
  traces: Dict[str, float]            # memory_key → eligibility trace
  values_at_access: Dict[str, float]  # memory_key → V(s) snapshot
  access_sequence: List[str]          # ordered access log
  grouped_baseline: GroupedValueBaseline  # HRPO baselines (Section 7)
```

**record_access(memory, step_reward=0.0):**

```
1. DECAY all traces:
   ∀k ∈ traces:  traces[k] *= γ · λ

2. PRUNE negligible traces:
   ∀k: if traces[k] < 10⁻⁸ → delete (Shannon: negligible information)

3. ACCUMULATE current state:
   traces[key] += 1.0

4. SNAPSHOT value:
   values_at_access[key] = V(s)
```

**end_episode(final_reward, memories):**

```
1. COMPUTE total reward:
   R_total = R_final + Σᵢ R_intermediate,i · γⁱ

2. GET group baseline (HRPO):
   b = GroupedValueBaseline.get_baseline(task_type, domain)

3. COMPUTE relative advantage:
   A = R_total - b

4. FOR each traced memory:
   V_old = values_at_access[key]
   δ = A - V_old                    # TD error
   ΔV = α · δ · e(key)             # Eligibility-weighted update
   V_new = clip(V_old + ΔV, 0, 1)  # Clamp to [0, 1]

5. UPDATE group baseline:
   b_new = (1 - α_ema) · b + α_ema · R_total
   where α_ema = 0.1
```

### 2.4 Single-Step TD(0) Update

For immediate (non-episodic) learning:

```
state_key = f"{{task_type}}:{{action_type}}"
V_old = baseline.get(state_key, 0.5)    # Default: neutral

IF terminal:
  δ = R - V_old
ELSE:
  V_next = baseline.get_baseline(task_type)
  δ = R + γ · V_next - V_old

V_new = V_old + α · δ
```

### 2.5 Default Hyperparameters

| Parameter | Symbol | Default | Range | Purpose |
|-----------|--------|---------|-------|---------|
| Discount factor | γ | 0.99 | [0.9, 0.999] | How much future rewards matter |
| Trace decay | λ | 0.95 | [0.9, 0.99] | Temporal credit propagation |
| Learning rate | α | adaptive | [0.001, 0.5] | Step size for value updates |
| Trace prune threshold | — | 10⁻⁸ | — | Remove negligible traces |
| Value clamp | — | [0, 1] | — | Keep values in valid range |

---

## 3. Q-Learning with Natural Language States

### 3.1 Overview

Jotty extends classical Q-learning to operate over **natural language state-action pairs**. Instead of discrete state indices, states are described as text (e.g., "coding task with web search tools") and actions as text (e.g., "use debate paradigm with temperature 0.7").

### 3.2 Q-Value Update Rule

```
target = R + γ · max_{a'} Q(s', a')
δ = target - Q(s, a)
Q(s, a) ← Q(s, a) + α · δ
Q(s, a) ∈ [0.0, 1.0]

where:
  α = 0.1     (learning rate)
  γ = 0.99    (discount factor)
```

### 3.3 Epsilon-Greedy Exploration

```
With probability ε = 0.15:
  a = random action                    (exploration)
With probability 1 - ε:
  a = argmax_a Q(task_type, a)         (exploitation)
```

### 3.4 Prioritized Experience Replay (PER)

Experiences with large TD errors are replayed more frequently:

```
priority(i) = (|δᵢ| + ε)^α_per

where:
  α_per = 0.6       (priority exponent)
  ε = 0.01          (minimum priority — no experience is zero-priority)

Sampling probability:
  P(i) = priority(i) / Σⱼ priority(j)

Importance sampling correction:
  wᵢ = (N · P(i))^{-β}

where:
  β = 0.4           (importance sampling exponent)
  N = replay buffer size
```

### 3.5 Q-Table Entry Structure

Each state-action pair stores rich metadata:

```
Q[key] = {{
    value: float,                    # Q-value ∈ [0, 1]
    context: List[Dict],             # Raw experiences
    learned_lessons: List[str],      # NL lessons extracted
    visit_count: int,                # Times visited
    avg_reward: float,               # Running average
    td_errors: List[float],          # Last 20 TD errors
    created_at: float,               # Timestamp
    last_updated: float              # Timestamp
}}
```

### 3.6 NeuroChunk Tiered Memory

Q-table entries are organized into 3 tiers based on retention score:

```
Retention Score = 0.4·Q_value + 0.3·novelty + 0.2·causal_impact - 0.1·staleness

where:
  novelty = 1 / (1 + visit_count)
  staleness = max(0, 1 - age_hours / 168)     # 1-week decay
  causal_impact = min(1, variance(td_errors) × 5)
  variance = Σ(δᵢ - μ)² / (n-1)
```

**Tier Allocation:**

| Tier | Name | Size | Contents |
|------|------|------|----------|
| 1 | Working Memory | Top 50 | Always in context window |
| 2 | Semantic Clusters | max 10 clusters | Retrieved by similarity |
| 3 | Archive | Remainder | Pruned by causal impact |

**Promotion Rule:** Tier 3 → Tier 2 when policy stalls (>10 episodes without improvement).

**Pruning:** When Q-table exceeds 10,000 entries, bottom 20% by retention score are removed.

---

## 4. Thompson Sampling — Bayesian Strategy Selection

### 4.1 The Multi-Armed Bandit Formulation

Jotty models execution parameter selection as a **contextual multi-armed bandit** problem:

- **Arms:** temperature values, model choices, paradigm choices, tool selections
- **Reward:** quality score ∈ [0, 1] from execution outcome
- **Context:** domain, task type, goal description

### 4.2 Beta Distribution Prior & Posterior

Each arm maintains a Beta distribution:

```
Prior:     Beta(α₀, β₀) = Beta(1, 1)     # Uniform (uninformed)

Update on execution with quality q:
  α_new = α_old + q                       # Accumulate reward
  β_new = β_old + (1 - q)                 # Accumulate failure

Posterior: Beta(α_new, β_new)

Expected value:  E[θ] = α / (α + β)
Variance:        Var[θ] = αβ / ((α+β)²(α+β+1))
```

### 4.3 Thompson Sampling Algorithm

```
FOR each arm a with parameters (α_a, β_a):
  θ̂_a ~ Beta(α_a, β_a)                   # Sample from posterior

SELECT:  a* = argmax_a θ̂_a                # Pick highest sample

EXECUTE with parameters from a*
OBSERVE quality q
UPDATE: α_{a*} += q,  β_{a*} += (1-q)
```

**Key insight:** Arms with few observations have **wide posteriors** (high variance) — they occasionally produce high samples, ensuring natural exploration. Well-tested arms have **tight posteriors** — they reliably produce samples near their true mean, ensuring exploitation.

### 4.4 Arm Space Definition

```
Temperature arms:   temp=0.3, temp=0.5, temp=0.7
Model arms:         model=gpt-4o, model=claude-3-opus, model=claude-sonnet, ...
Paradigm arms:      paradigm=direct, paradigm=relay, paradigm=debate, paradigm=refinement
Tool arms:          tools=web-search, tools=calculator, ...
```

### 4.5 Cold Start Handling

```
IF successful_episodes < 2:
  # Phase 1: Pure exploration
  temperature = random.choice([0.3, 0.5, 0.7])
  paradigm = random.choice(["direct", "relay", "debate", "refinement"])
  strategy = "thompson_cold_start"
  exploration = True

ELIF arm.n < 3:
  # Phase 2: Under-explored arm
  Use Thompson Sampling but flag as exploration
  exploration_reason = f"thompson: {{arm}} under-explored (n={{arm.n}})"

ELSE:
  # Phase 3: Full Thompson Sampling
  Use posterior samples for all decisions
  strategy = "thompson_sampling"
```

### 4.6 Untried Arm Injection

```
untried_paradigms = available_paradigms - tried_paradigms

IF untried_paradigms is not empty AND random() < 0.3:
  paradigm = random.choice(untried_paradigms)
  exploration = True
  reason = f"thompson: trying untried paradigm={{paradigm}}"
```

This 30% injection rate ensures complete paradigm coverage over time.

### 4.7 Paradigm Selection (Swarm Level)

```
FOR paradigm ∈ ["direct", "relay", "debate", "refinement", "fanout"]:
  stats = bucket.get(paradigm, {{runs: 0, successes: 0}})

  IF stats.runs == 0:
    score = random()                          # Cold start: uniform
  ELSE:
    failures = stats.runs - stats.successes
    score ~ Beta(successes + 1, failures + 1) # Thompson sampling

best_paradigm = argmax(score)
```

---

## 5. Shaped Rewards — Dense Intermediate Signals

### 5.1 The Sparse Reward Problem

In complex multi-step tasks, the final success/failure signal is too sparse for efficient learning. Shaped rewards provide **dense intermediate signals** at key checkpoints.

### 5.2 Reward Schedule

| Event | Trigger | Reward | Condition |
|-------|---------|--------|-----------|
| Input validated | actor_start | +0.05 | confidence ≥ 0.7 |
| Dependency resolved | actor_start | +0.05 | confidence ≥ 0.7 |
| Tool call success | tool_call (repeating) | +0.10 | confidence ≥ 0.7 |
| Partial output | actor_complete | +0.10 | confidence ≥ 0.7 |
| Full output | actor_complete | +0.15 | confidence ≥ 0.7 |
| Validation passed | validation | +0.20 | confidence ≥ 0.7 |
| Execution success | tool_call | +0.25 | confidence ≥ 0.7 |
| Goal achieved | actor_complete | +0.50 | confidence ≥ 0.7 |

### 5.3 Confidence Gating

Each condition is evaluated by an LLM or rule-based checker:

```
reward_given = reward_value × confidence    IF confidence ≥ 0.7
reward_given = 0                            IF confidence < 0.7
```

### 5.4 Discounted Intermediate Sum

```
R_intermediate = Σᵢ rᵢ · γⁱ

where:
  rᵢ = shaped reward at step i
  γ = 0.99 (same discount factor as TD-Lambda)
```

### 5.5 Total Reward

```
R_total = R_terminal + R_intermediate

where:
  R_terminal = +1.0 (success) or -0.5 (failure)
  R_intermediate = Σ shaped rewards (discounted)
```

---

## 6. Credit Assignment — Shapley Values & Counterfactual Analysis

### 6.1 The Multi-Agent Credit Problem

When N agents collaborate, how do we attribute the final reward to individual contributions?

### 6.2 Shapley Value (Exact)

From cooperative game theory, the Shapley value gives the **unique fair allocation** satisfying symmetry, efficiency, and null player axioms:

```
φᵢ = Σ_{S⊆N\{{i}}} |S|!(n-|S|-1)! / n! × [v(S∪{{i}}) - v(S)]

where:
  n = number of agents
  S = subset of agents NOT including i
  v(S) = value (reward) produced by coalition S
  v(S∪{{i}}) - v(S) = marginal contribution of agent i to coalition S
```

### 6.3 Monte Carlo Shapley Approximation

Exact Shapley is O(2ⁿ). Jotty uses Monte Carlo sampling:

```
num_samples = max(10, min(5·n!, 100))

FOR s = 1 to num_samples:
  π = random_permutation(agents)
  FOR each agent i in π:
    S = agents before i in π
    marginal[i][s] = v(S ∪ {{i}}) - v(S)

φᵢ = (1/num_samples) · Σₛ marginal[i][s]
```

### 6.4 Confidence Interval (95%)

```
variance = (1/(n-1)) · Σ(marginal[i][s] - φᵢ)²
std_error = √(variance / n)
ci_half = 1.96 × std_error
confidence = max(0, min(1, 1 - ci_half))
```

### 6.5 Difference Rewards (Counterfactual)

An alternative credit method based on the question: "What would have happened without agent i?"

```
Dᵢ = G - G_{-i}

where:
  G = global reward (with all agents)
  G_{-i} = estimated reward without agent i (via LLM estimation)
```

### 6.6 Combined Credit (Adaptive Weighting)

```
shapley_weight = 0.3 + 0.4 × confidence     # ∈ [0.3, 0.7]

combined = shapley_weight × φᵢ + (1 - shapley_weight) × Dᵢ
```

Higher confidence in Shapley estimates → more weight on Shapley.
Lower confidence → fallback toward simpler difference rewards.

### 6.7 Normalization

```
credit(i) = (combined(i) / Σⱼ combined(j)) × G

Ensures: Σᵢ credit(i) = G    (efficiency axiom)
```

### 6.8 COMA — Counterfactual Multi-Agent Credit

Simplified version used for per-agent tracking:

```
credit(agent) = avg_reward_when_present - avg_reward_when_absent

State:
  _history[agent]: List[(team_reward, agent_contribution)]    # max 200
  _counterfactual[agent]: List[reward_when_absent]            # max 200
```

---

## 7. HRPO Group-Relative Baselines

### 7.1 Motivation

Raw rewards have high variance across task types. A coding task scoring 0.8 may be excellent, while a research task scoring 0.8 may be mediocre. Group baselines normalize rewards relative to task-type expectations.

### 7.2 Exponential Moving Average (EMA) Update

```
b_new = (1 - α_ema) · b_old + α_ema · R

where:
  α_ema = 0.1    (baseline update rate)
  R = observed reward
  b = group baseline for task_type
```

### 7.3 Hierarchical Baseline Lookup

```
1. IF group_counts[f"{{task_type}}:{{action_type}}"] ≥ 3:
     RETURN group_baselines[f"{{task_type}}:{{action_type}}"]

2. ELIF group_counts[task_type] ≥ 3:
     RETURN group_baselines[task_type]

3. ELIF domain_baselines[domain] exists:
     RETURN domain_baselines[domain]

4. ELIF transfer_matrix has similar tasks:
     RETURN weighted_average(transfer_baselines)

5. DEFAULT: RETURN 0.5    (neutral expectation)
```

### 7.4 Transfer Weight Update

```
similarity = 1.0 - min(1.0, |μ_other - μ_current|)
w_new = 0.9 · w_old + 0.1 · similarity

weighted_baseline = Σⱼ (wⱼ · bⱼ) / Σⱼ wⱼ
```

### 7.5 Relative Advantage

```
A(s, a) = R - b(task_type)

A > 0: Better than average → reinforce
A < 0: Worse than average → suppress
A ≈ 0: Typical → small update
```

---

## 8. Adaptive Learning Rate

### 8.1 Adaptation Rules

```
RULE 1 — Unstable (high variance):
  IF std_dev > mean_error × 1.2:
    adjustment -= adaptation_rate         # Slow down

RULE 2 — Stagnant (low error):
  ELIF mean_error < 0.1:
    adjustment += adaptation_rate × 2.0   # Speed up

RULE 3 — Declining performance:
  IF recent_success < older_success - 0.1:
    adjustment += adaptation_rate × 0.5   # Adapt faster
```

### 8.2 Update Formula

```
α_new = α_old × (1 + adjustment)
α ∈ [α_min, α_max] = [0.001, 0.5]
```

### 8.3 Statistics Used

```
mean_error = (1/n) · Σ|δᵢ|              # Average absolute TD error
variance = (1/n) · Σ(δᵢ - μ)²           # TD error variance
std_dev = √variance                      # Standard deviation
```

### 8.4 LearningService Decaying Rate

In the `LearningService._update_values()`:

```
α = max(0.01, 0.1 / (1 + update_count × 0.01))

This decays from 0.1 toward 0.01 as more updates accumulate,
implementing a Robbins-Monro-style schedule:
  Σ αₜ = ∞  (explores forever)
  Σ αₜ² < ∞  (converges)
```

---

## 9. Multi-Agent Swarm Learning Lifecycle

### 9.1 Pre-Execution Learning Hook

```
_pre_execute_learning():
  1. Auto-connect SwarmIntelligence
  2. Auto-warmup on first run (cold-start initialization)
  3. Compute MorphAgent scores: RCS, RDS, TRAS for all agents
  4. Analyze tool success rates via ToolManager
  5. STITCH: combine weak tools + inconsistent agents → recommendations
  6. Retrieve expert domain knowledge from SwarmMemory
  7. Analyze prior failures for recovery patterns
  8. Compute score trends (improving vs declining)
  9. Run coordination protocols:
     - Circuit breakers (per-agent failure tracking)
     - Gossip protocols (disseminate learnings)
     - Auctions (task allocation)
     - Coalition formation (temporary teams)
     - Supervisor tree building
     - Backpressure calculation

  RETURNS: Dict with learned_context for all agents
```

### 9.2 Post-Execution Learning Hook

```
_post_execute_learning(success, execution_time, tools_used, output_data):
  1. Send executor feedback to SwarmIntelligence
     - Classify error type: invalid_input / timeout / infrastructure / auth / execution_failure

  2. Recompute MorphAgent scores with new data
     - Update morph_score_history (deque, maxlen=100)
     - Track RCS/RDS/TRAS deltas

  3. Re-analyze tools and update assignments

  4. Post-execution coordination:
     - Byzantine verification: claimed_success vs actual_result
     - Circuit breaker updates
     - Gossip broadcast: disseminate learnings
     - Coalition cleanup
     - Load balancing: work rebalancing

  5. Evaluate output against gold standard
     IF score ≥ 0.9: auto-curate as gold standard
     Extract learnings: patterns from excellent executions

  6. Record episode via LearningService.record()

  7. TD-Lambda update at swarm level
```

### 9.3 Quality Scoring

```
quality = evaluation.overall_score    IF available
quality = 1.0                         IF success (no evaluator)
quality = 0.0                         IF failure
```

### 9.4 Gold Standard Auto-Curation

```
IF quality ≥ 0.9:
  Store (input, output, quality) as gold reference
  Limit: max_version per task_type
  Future agents see this as exemplar
```

---

## 10. Team Coordination Patterns & Learning Signals

### 10.1 Eight Coordination Patterns

| # | Pattern | Algorithm | Reward Attribution |
|---|---------|-----------|-------------------|
| 1 | **PIPELINE** | Output_i → Input_{i+1} | Clear per-agent credit (schema-aware wiring) |
| 2 | **PARALLEL** | All agents concurrently | Ambiguous (averaging masks individual credit) |
| 3 | **CONSENSUS** | Parallel + majority voting | Majority voters: +reward, Outliers: -reward |
| 4 | **DEBATE** | Multi-round deliberation | Round-by-round improvement tracking |
| 5 | **ITERATIVE** | Parallel → Evaluate → Improve → Repeat | Per-round quality delta |
| 6 | **HIERARCHICAL** | Manager delegates → Workers execute | Manager: delegation quality, Workers: execution |
| 7 | **BLACKBOARD** | Shared state, contribute until done | Per-round contribution tracking |
| 8 | **ROUND_ROBIN** | Agents take turns | Simple per-subtask success/failure |

### 10.2 Schema-Aware Pipeline Wiring

```
Agent₁.outputs = ["design"]
Agent₂.inputs = ["design"]

Wire: Agent₁.output["design"] → Agent₂.input["design"]

Learning benefit: clear causal chain
  → precise reward attribution per agent
  → each agent's V(s) updated independently
```

### 10.3 Debate Pattern — Multi-Round Learning

```
Round 1: All agents propose solutions (PARALLEL)
  reward_1(agent_i) = proposal_quality(agent_i)

Round 2..N: Each agent critiques and refines
  reward_k(agent_i) = quality(round_k) - quality(round_{k-1})

Final: Synthesize best solution
  synthesis_reward = quality(synthesis)

Backpropagation:
  credit(agent_i) = Σ_k (synthesis_reward / num_rounds)
  ∀ rounds where agent_i participated
```

### 10.4 Parallel Merge Strategies

| Strategy | Formula | Learning Impact |
|----------|---------|----------------|
| COMBINE | merged = all_outputs | Ambiguous credit |
| CONCAT | merged = join(outputs) | Order-dependent |
| VOTE | merged = mode(outputs) | Binary: voted with majority or not |
| BEST | merged = argmax(quality) | Winner-take-all |

---

## 11. Stigmergy — Emergent Pheromone-Based Routing

### 11.1 Concept

Borrowed from ant colony optimization: agents leave "pheromone" signals after completing tasks. Other agents sense these signals to route future tasks.

### 11.2 Signal Deposit

```
Signal = {{
  signal_id: md5(type:content:agent:time),
  signal_type: "success" | "warning" | "route" | "resource",
  content: Any,
  strength: S₀ ∈ [0, 1],
  created_by: agent_name,
  metadata: Dict
}}
```

### 11.3 Temporal Decay

```
S(t) = S₀ × max(0, 1 - decay_rate × Δt_hours)

where:
  decay_rate = 0.1 (per hour)
  Δt_hours = (now - created_at) / 3600

Example:
  S₀ = 1.0, after 5 hours: S(5) = 1.0 × (1 - 0.1 × 5) = 0.5
  After 10 hours: S(10) = 0 (fully decayed)
```

### 11.4 Signal Sensing

```
sense(signal_type, min_strength=0.1):
  1. Apply decay to all signals
  2. Filter: strength ≥ min_strength AND type matches
  3. Sort by strength (strongest first)
  RETURN: List[Signal]
```

### 11.5 Emergent Task Routing

```
task_routing_score(agent, task_type) =
  Σ signal.strength
  ∀ signal ∈ sense("success")
  where signal.content.task_type == task_type
        AND signal.created_by == agent

best_agent = argmax_agent(task_routing_score)
```

Over time, successful agent-task pairings accumulate strong signals while failed pairings decay. This creates **emergent specialization** without a central coordinator.

---

## 12. MorphAgent Scoring (RCS/RDS/TRAS)

### 12.1 Reasoning Capability Score (RCS)

```
RCS = 0.4 × consistency + 0.3 × focus + 0.3 × specialization

where:
  consistency = success_rate (tasks completed without errors)
  focus = 1 - entropy(agent_tasks) / log(|task_types|)
  specialization = max_domain_fraction (share of top domain)
```

### 12.2 Reasoning Diversity Score (RDS)

```
RDS = H(domains) = -Σ p(d) · log₂ p(d)

where:
  p(d) = fraction of tasks in domain d

High RDS: generalist (works across many domains)
Low RDS: specialist (focused on few domains)
```

### 12.3 Task Relevance Adaptation Score (TRAS)

```
TRAS = success_rate_relevant - success_rate_irrelevant

Measures how much performance adapts to task relevance.
High TRAS: strong context sensitivity
Low TRAS: performance independent of task match
```

### 12.4 Score Tracking

```
morph_score_history: deque(maxlen=100)

Trend detection:
  improving = mean(last_10) > mean(first_10) + 0.05
  declining = mean(last_10) < mean(first_10) - 0.05
  stable = otherwise
```

---

## 13. Agent Execution Pipeline & Learning Integration

### 13.1 Six-Stage Pipeline (AgentRunner)

```
STAGE 1: SETUP
  ├── Validation gate decision (DIRECT / AUDIT_ONLY / FULL)
  ├── Task progress tracker initialization
  └── TD-Lambda episode start

STAGE 2: GATHER LEARNING CONTEXT (8000 char budget)
  ├── Memory retrieval (3000 tokens, keyword+recency+value, NO LLM)
  ├── Q-Learning context
  ├── Transfer learning patterns
  └── Swarm intelligence hints (trust score, stigmergy, collective memory)
  → IF total > 8000 chars: compress (extract key facts, fair-share truncate)

STAGE 3: ARCHITECT VALIDATION (pre-execution)
  ├── Task-specific prompt selection
  ├── Multi-round validation
  └── Shaped reward: architect_proceed × confidence

STAGE 4: EXECUTE AGENT
  ├── Cache check (md5 hash, 30-min TTL)
  ├── Execute via agent.execute() / agent.forward() / callable
  └── Build trajectory: [{{step, skill, action, success, output}}]

STAGE 5: AUDITOR VALIDATION + JUDGE RETRY
  ├── Post-execution quality check
  ├── IF failed AND confidence < 0.6:
  │     Judge feedback → retry agent with learning context
  │     (MALLM-inspired turn regeneration, max 1 retry)
  └── Shaped reward: validation_passed × confidence

STAGE 6: RECORD LEARNING
  ├── Store episodic memory (goal + output[:500])
  ├── TD-Lambda: record_access() + end_episode()
  ├── Q-Learning: record_outcome(state, action, reward)
  ├── Shaped reward aggregation: R_total = R_terminal + R_shaped
  ├── Executor feedback → SwarmIntelligence
  ├── Byzantine verification (catch false successes)
  ├── Stigmergy: record outcome for emergent routing
  └── MAS Learning: record session for strategy recommendations
```

### 13.2 Learning Context Injection Gates

The system uses **adaptive gates** to avoid polluting capable models:

```
Injection Gate:
  IF success_rate ≥ 90% AND total_episodes ≥ 5:
    → NO injection (model already succeeds)

  IF total_episodes < 5:
    → Cold start injection (best approach template)

  IF success_rate < 90% AND total_episodes ≥ 5:
    → Failure correction injection (common failure modes + best approach)

Retrieval Gate (stricter):
  ONLY inject IF success_rate < 90% AND total_episodes ≥ 5
  → Prior successful response structures (top-2 by similarity)
```

### 13.3 Reward Signal Composition

```
R_terminal    = +1.0 (success) or -0.5 (failure)
R_architect   = +0.05 × confidence                    (if validation passed)
R_tool        = +0.10 × Σ(tool successes)             (per tool call)
R_auditor     = +0.20 × confidence                    (if audit passed)
R_goal        = +0.50 × confidence                    (if goal achieved)

R_total = R_terminal + R_architect + R_tool + R_auditor + R_goal
        ∈ [-0.5, ~2.5] typically
```

---

## 14. Transfer Learning Across Domains

### 14.1 Relevance Scoring

```
relevance(session, query) =
  0.4 × topic_overlap +
  0.2 × agent_overlap +
  0.2 × recency +
  0.2 × success_bonus

where:
  topic_overlap = |query_topics ∩ session_topics| / |query_topics|
  agent_overlap = |query_agents ∩ session_agents| / |query_agents|
  recency = max(0, 1 - days_old / 30)       # 30-day decay
  success_bonus = 0.2 if session.success else 0

Filter: relevance > 0.3 (minimum threshold)
```

### 14.2 Execution Strategy Recommendation

```
FOR each available agent:
  IF agent in learned_successful_agents:
    score = historical_success_rate
  ELSE:
    score = 0.5                              # Default for unknown agents

Skip agents with success_rate < 0.4
Rank remaining by score (descending)
Confidence = min(1.0, similar_task_count / 5)
```

### 14.3 Cross-Domain Value Transfer

```
similarity(domain_A, domain_B) = 1 - min(1, |μ_A - μ_B|)

transfer_weight_new = 0.9 × transfer_weight_old + 0.1 × similarity

baseline(new_domain) = Σⱼ (wⱼ × bⱼ) / Σⱼ wⱼ
  where j iterates over known domains
```

---

## 15. Convergence Properties & Plateau Detection

### 15.1 Convergence Detection

```
converged IF:
  score_history[-1] ≥ 0.9 AND |score[-1] - score[-2]| < 0.05

Actions at convergence:
  learning_rate *= 0.9                # Fine-tuning mode
  exploration_rate -= 0.1              # Exploit proven strategies
```

### 15.2 Plateau Detection

```
plateau IF:
  variance(score_history[-5:]) < 0.01 AND
  improvement_velocity ≤ 0.01 AND
  mean(score_history[-5:]) < 0.9

Actions at plateau:
  learning_rate *= 1.2                # Escape local optima
  exploration_rate += 0.1              # Discover new strategies
  Tier 3 → Tier 2 promotion in Q-table  # Revisit archived knowledge
```

### 15.3 Improvement Velocity

```
velocities = [score[t] - score[t-1] for t in range(-5, 0)]
improvement_velocity = mean(velocities)

velocity > 0.05:  accelerating (reduce exploration)
velocity ≈ 0:     plateau (increase exploration)
velocity < -0.05: declining (adapt faster)
```

### 15.4 Theoretical Guarantees

Under standard RL assumptions:
- Decaying learning rate: α_t = 0.1 / (1 + n × 0.01) satisfies Σα_t = ∞, Σα_t² < ∞
- Bounded rewards: R ∈ [-0.5, ~2.5]
- Stationary reward distribution per task type
- → **Value estimates converge** to true expected rewards

Thompson Sampling converges to optimal arm selection with **logarithmic regret**:
```
Regret(T) = O(K × log(T) / Δ_min)

where:
  K = number of arms
  T = number of rounds
  Δ_min = minimum gap between optimal and sub-optimal arms
```

---

## 16. Episode Data Model & Storage

### 16.1 EpisodeRecord

```
EpisodeRecord:
  episode_id: str          # "ep_{{unit_name}}_{{timestamp}}_{{uuid6}}"
  unit_type: str           # "agent" | "swarm" | "pipeline" | "orchestrator"
  unit_name: str           # e.g., "CodingSwarm", "ResearchAgent"
  domain: str              # e.g., "coding", "research", "economics"
  task_type: str           # e.g., "code_generation", "stock_analysis"
  context: Dict            # Truncated task description + inputs
  action: Dict             # {{temperature, model, paradigm, tools_used, strategy, exploration}}
  outcome: Dict            # Results produced
  success: bool
  quality: float           # 0.0 - 1.0
  execution_time: float    # Seconds
  cost: float              # USD (LLM call costs)
  error_type: str | None   # Classified error category
  error_message: str | None  # Truncated to 500 chars
  parent_episode_id: str | None  # For nested episodes
  timestamp: float         # Unix timestamp
  metadata: Dict           # Additional data
```

### 16.2 ValueEstimate

```
ValueEstimate:
  state_key: str           # "{{domain}}:{{task_type}}"
  action_key: str          # Serialized action parameters
  domain: str
  value: float             # V(s,a) ∈ [0, 1]
  td_error: float          # Last δ
  update_count: int        # Number of updates
```

### 16.3 Storage Backend

- **SQLite** (default): `~/.jotty/learning/episodes.db`
- JSON fallback for simple deployments
- Persistent across sessions
- Query by domain, task_type, time range, success filter

---

## 17. Complete Learning Loop — End to End

```
USER INPUT: "Research AI trends"
    │
    ▼
[1] TIER EXECUTOR: classify intent → RESEARCH tier
    │
    ▼
[2] LEARNING SERVICE: get_optimal_execution_params("research", "research")
    │  Thompson Sampling: Beta(3.2, 1.1) for temp=0.5 → sample 0.78
    │  Thompson Sampling: Beta(2.0, 1.5) for paradigm=debate → sample 0.61
    │  → temperature=0.5, paradigm=debate, strategy="thompson_sampling"
    │
    ▼
[3] SWARM MANAGER: execute ResearchSwarm with learned parameters
    │
    ▼
[4] PRE-EXECUTE LEARNING:
    │  MorphAgent scores: DataFetcher RCS=0.85, Analyst RCS=0.92
    │  Tool health: web-search HEALTHY (96%), calculator DEGRADED (78%)
    │  Stigmergy: DataFetcher has strongest "success" signal for research
    │  Prior failure: "timeout on large datasets" → inject warning
    │
    ▼
[5] AGENT RUNNER (per agent):
    │
    │  GATHER CONTEXT (8000 char budget):
    │    Memory: 3 relevant episodic memories (1200 chars)
    │    Q-table: "research → debate worked well (Q=0.82)" (400 chars)
    │    Transfer: "economics research pattern applicable" (600 chars)
    │    SI hints: "You're top-3 for research tasks" (200 chars)
    │
    │  EXECUTE AGENT → output
    │
    │  SHAPED REWARDS:
    │    architect_validation: +0.05 (proceed=True, confidence=0.9)
    │    tool_success: +0.10 × 3 tools = +0.30
    │    auditor_validation: +0.20 (passed, confidence=0.85)
    │
    │  TD-LAMBDA UPDATE:
    │    R_total = 1.0 + 0.05 + 0.30 + 0.20 = 1.55
    │    baseline("research") = 0.72
    │    advantage = 1.55 - 0.72 = 0.83
    │
    │    For traced memory m₁ (e=0.95):
    │      δ = 0.83 - V(m₁)
    │      V(m₁) ← V(m₁) + α × δ × 0.95
    │    For traced memory m₂ (e=0.90):
    │      V(m₂) ← V(m₂) + α × δ × 0.90
    │
    ▼
[6] POST-EXECUTE LEARNING:
    │  Byzantine: output verified genuine
    │  Credit: Shapley φ = [DataFetcher: 0.35, Analyst: 0.45, Synthesizer: 0.20]
    │  Gold standard: quality=0.92 ≥ 0.9 → auto-curate
    │  Gossip: broadcast success pattern to all agents
    │  Stigmergy: deposit success signal (strength=0.92)
    │
    ▼
[7] LEARNING SERVICE: record episode
    │  domain="research", quality=0.92, cost=$0.08
    │  Update Beta: α(temp=0.5) += 0.92, β(temp=0.5) += 0.08
    │  Update Beta: α(paradigm=debate) += 0.92, β(paradigm=debate) += 0.08
    │  Update baseline: b("research") = 0.9 × 0.72 + 0.1 × 0.92 = 0.74
    │
    ▼
[8] NEXT EXECUTION: Thompson posteriors are tighter
    temp=0.5: Beta(4.12, 1.18) → E[θ] = 0.78 (more confident)
    paradigm=debate: Beta(2.92, 1.58) → E[θ] = 0.65 (debate working)
    → System increasingly exploits what works
    → Under-explored arms (temp=0.3) still occasionally sampled
```

---

*This document was generated by analyzing {lines} lines of learning code across {files} files in the Jotty codebase. Every formula corresponds to actual implemented code.*
"""


def markdown_to_pdf(md_content: str, output_path: str) -> str:
    """Convert markdown to professional PDF."""
    import markdown as md_lib
    from weasyprint import HTML

    html_body = md_lib.markdown(
        md_content,
        extensions=["tables", "fenced_code", "codehilite", "toc", "nl2br"],
    )

    css = """
    @page {
        size: A4;
        margin: 1.8cm 2cm;
        @bottom-center {
            content: "Jotty Learning System — Page " counter(page) " of " counter(pages);
            font-size: 8.5px; color: #666;
            font-family: 'Segoe UI', Arial, sans-serif;
        }
    }
    body {
        font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
        font-size: 10.5pt; line-height: 1.55; color: #1a1a1a;
    }
    h1 { font-size: 24pt; color: #1a365d; border-bottom: 3px solid #2b6cb0;
         padding-bottom: 10px; margin-top: 0; }
    h2 { font-size: 16pt; color: #2b6cb0; border-bottom: 1.5px solid #bee3f8;
         padding-bottom: 5px; margin-top: 28px; page-break-after: avoid; }
    h3 { font-size: 13pt; color: #2c5282; margin-top: 18px; page-break-after: avoid; }
    p { margin: 6px 0; text-align: justify; }
    table { border-collapse: collapse; width: 100%; margin: 12px 0;
            font-size: 9.5pt; page-break-inside: avoid; }
    th { background-color: #2b6cb0; color: white; padding: 7px 10px;
         text-align: left; font-weight: 600; }
    td { padding: 5px 10px; border-bottom: 1px solid #e2e8f0; }
    tr:nth-child(even) td { background-color: #f7fafc; }
    code { background-color: #edf2f7; padding: 1px 5px; border-radius: 3px;
           font-size: 9pt; font-family: 'Consolas', 'Monaco', monospace; color: #c53030; }
    pre { background-color: #1a202c; color: #e2e8f0; padding: 14px;
          border-radius: 6px; font-size: 8.5pt; line-height: 1.45;
          page-break-inside: avoid; margin: 10px 0; white-space: pre-wrap; }
    pre code { background: none; color: #e2e8f0; padding: 0; }
    ul, ol { padding-left: 22px; margin: 6px 0; }
    li { margin: 2px 0; }
    strong { color: #1a365d; }
    hr { border: none; border-top: 1px solid #cbd5e0; margin: 22px 0; }
    blockquote { border-left: 4px solid #2b6cb0; margin: 10px 0; padding: 6px 14px;
                 background-color: #ebf8ff; font-style: italic; }
    """

    full_html = f"<!DOCTYPE html><html><head><meta charset='utf-8'><style>{css}</style></head><body>{html_body}</body></html>"
    HTML(string=full_html).write_pdf(output_path)
    return output_path


async def send_telegram(file_path: str, caption: str):
    """Send PDF to Telegram."""
    import aiohttp
    token = os.environ.get("TELEGRAM_TOKEN") or os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")
    if not token or not chat_id:
        print("  No TELEGRAM_TOKEN/TELEGRAM_CHAT_ID")
        return None
    url = f"https://api.telegram.org/bot{token}/sendDocument"
    async with aiohttp.ClientSession() as session:
        with open(file_path, "rb") as f:
            data = aiohttp.FormData()
            data.add_field("chat_id", chat_id)
            data.add_field("caption", caption[:1024])
            data.add_field("document", f, filename=os.path.basename(file_path))
            async with session.post(url, data=data) as resp:
                r = await resp.json()
                return r


async def main():
    start = time.time()
    print("=" * 70)
    print("  JOTTY LEARNING DEEP DIVE — Generating PDF with Full Math")
    print("=" * 70)

    # Count learning files
    import glob
    learning_files = glob.glob(str(JOTTY_ROOT / "core/intelligence/learning/*.py"), recursive=True)
    orch_learning = glob.glob(str(JOTTY_ROOT / "core/intelligence/orchestration/learning/*.py"), recursive=True)
    swarm_base = glob.glob(str(JOTTY_ROOT / "core/intelligence/orchestration/swarms/_base/*.py"), recursive=True)
    swarm_base2 = glob.glob(str(JOTTY_ROOT / "core/intelligence/orchestration/swarms/base/*.py"), recursive=True)
    all_files = learning_files + orch_learning + swarm_base + swarm_base2
    total_lines = 0
    for f in all_files:
        try:
            with open(f, errors="ignore") as fh:
                total_lines += sum(1 for _ in fh)
        except Exception:
            pass

    now = datetime.now().strftime("%B %d, %Y")
    md_content = MARKDOWN.replace("{date}", now).replace("{lines}", f"{total_lines:,}").replace("{files}", str(len(all_files)))

    # Save markdown
    md_path = str(JOTTY_ROOT / "outputs" / "Jotty_Learning_Deep_Dive.md")
    os.makedirs(os.path.dirname(md_path), exist_ok=True)
    with open(md_path, "w") as f:
        f.write(md_content)
    print(f"  Markdown: {md_path} ({len(md_content):,} chars)")

    # Generate PDF
    print("  Generating PDF...")
    pdf_path = str(JOTTY_ROOT / "outputs" / "Jotty_Learning_Deep_Dive.pdf")
    try:
        markdown_to_pdf(md_content, pdf_path)
        pdf_size = os.path.getsize(pdf_path)
        print(f"  PDF: {pdf_path} ({pdf_size / 1024:.0f} KB)")
    except Exception as e:
        print(f"  PDF failed: {e}")
        pdf_path = None

    # Send to Telegram
    if pdf_path:
        print("  Sending to Telegram...")
        result = await send_telegram(
            pdf_path,
            f"Jotty Learning System — Complete Mathematical Deep Dive\n"
            f"17 sections | TD(λ), Q-Learning, Thompson Sampling, Shapley Values\n"
            f"{total_lines:,} lines of learning code across {len(all_files)} files\n"
            f"Generated {now}"
        )
        if result and result.get("ok"):
            print("  Telegram: Sent!")
        else:
            print(f"  Telegram: {result}")

    elapsed = time.time() - start
    print(f"\n  DONE in {elapsed:.1f}s")
    if pdf_path:
        print(f"  PDF: {pdf_path}")


if __name__ == "__main__":
    asyncio.run(main())
