"""
research-to-pdf: Research a topic and generate PDF report using Jotty skills.

This skill combines:
- last30days-claude-cli: Research topics from last 30 days
- document-converter: Convert markdown to PDF
"""

import asyncio
from pathlib import Path
from datetime import datetime
from typing import Dict, Any
import logging

logger = logging.getLogger(__name__)


async def research_to_pdf_tool(params: Dict[str, Any]) -> Dict[str, Any]:
    """
    Research a topic and generate a PDF report.
    
    Args:
        params: Dictionary containing:
            - topic (required): Topic to research
            - output_dir (optional): Output directory (default: ~/jotty/reports)
            - title (optional): Report title (default: auto-generated from topic)
            - author (optional): Report author (default: 'Jotty Framework')
            - page_size (optional): PDF page size - 'a4', 'a5', 'a6', 'letter' (default: 'a4')
            - deep (optional): Deep research mode (default: False)
            - quick (optional): Quick research mode (default: False)
    
    Returns:
        Dict with:
            - success (bool): Whether operation succeeded
            - pdf_path (str): Path to generated PDF
            - md_path (str): Path to markdown file
            - file_size (int): PDF file size in bytes
            - error (str, optional): Error message if failed
    """
    try:
        from core.registry.skills_registry import get_skills_registry
        
        topic = params.get('topic', '')
        if not topic:
            return {
                'success': False,
                'error': 'topic parameter is required'
            }
        
        registry = get_skills_registry()
        registry.init()
        
        # Step 1: Research
        logger.info(f"Researching topic: {topic}")
        last30days_skill = registry.get_skill('last30days-claude-cli')
        if not last30days_skill:
            return {
                'success': False,
                'error': 'last30days-claude-cli skill not found'
            }
        
        research_tool = last30days_skill.tools.get('last30days_claude_cli_tool')
        if not research_tool:
            return {
                'success': False,
                'error': 'last30days_claude_cli_tool not found'
            }
        
        # Determine research depth
        deep = params.get('deep', False)
        quick = params.get('quick', False)
        
        research_result = await research_tool({
            'topic': topic,
            'deep': deep,
            'quick': quick,
            'emit': 'md'  # Get markdown format
        })
        
        if not research_result.get('success'):
            return {
                'success': False,
                'error': f'Research failed: {research_result.get("error")}'
            }
        
        research_content = research_result.get('output', '')
        
        # Step 2: Create markdown file
        output_dir = Path(params.get('output_dir', str(Path.home() / 'jotty' / 'reports')))
        output_dir.mkdir(parents=True, exist_ok=True)
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        safe_topic = topic.replace(' ', '_').replace('/', '_')[:50]  # Sanitize filename
        md_file = output_dir / f'{safe_topic}_research_{timestamp}.md'
        
        # Generate report title
        report_title = params.get('title', f'{topic.title()} Research Report')
        author = params.get('author', 'Jotty Framework')
        
        # Create comprehensive markdown report
        report_content = f"""# {report_title}

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Research Period:** Last 30 days
**Source:** Jotty last30days-claude-cli skill
**Author:** {author}

---

{research_content}

---

## Report Metadata

- **Research Tool:** last30days-claude-cli (Jotty)
- **Search Engine:** DuckDuckGo via ddgs library
- **Generated by:** Jotty Framework
- **Format:** Markdown → PDF
- **Topic:** {topic}
"""
        
        md_file.write_text(report_content)
        logger.info(f"Markdown file created: {md_file}")
        
        # Step 3: Convert to PDF
        logger.info("Converting markdown to PDF")
        doc_converter_skill = registry.get_skill('document-converter')
        if not doc_converter_skill:
            return {
                'success': False,
                'error': 'document-converter skill not found'
            }
        
        pdf_tool = doc_converter_skill.tools.get('convert_to_pdf_tool')
        if not pdf_tool:
            return {
                'success': False,
                'error': 'convert_to_pdf_tool not found'
            }
        
        page_size = params.get('page_size', 'a4')
        pdf_result = pdf_tool({
            'input_file': str(md_file),
            'output_file': str(md_file.with_suffix('.pdf')),
            'title': report_title,
            'author': author,
            'page_size': page_size
        })
        
        if not pdf_result.get('success'):
            return {
                'success': False,
                'error': f'PDF conversion failed: {pdf_result.get("error")}',
                'md_path': str(md_file)
            }
        
        pdf_path = pdf_result.get('output_path')
        file_size = pdf_result.get('file_size', 0)
        
        return {
            'success': True,
            'pdf_path': pdf_path,
            'md_path': str(md_file),
            'file_size': file_size,
            'topic': topic,
            'title': report_title
        }
        
    except Exception as e:
        logger.error(f"Error in research_to_pdf_tool: {e}", exc_info=True)
        return {
            'success': False,
            'error': str(e)
        }

__all__ = ['research_to_pdf_tool']
