#!/usr/bin/env python3
"""
Test SDK Generation and Validation

This script tests the SDK generation process and validates the generated code.
"""

import json
import subprocess
import sys
from pathlib import Path


def validate_openapi_spec(spec_path: Path) -> bool:
    """Validate OpenAPI specification."""
    print(f"📋 Validating OpenAPI spec: {spec_path}")
    
    if not spec_path.exists():
        print(f"❌ Spec file not found: {spec_path}")
        return False
    
    try:
        with open(spec_path) as f:
            spec = json.load(f)
        
        # Basic validation
        required_fields = ["openapi", "info", "paths"]
        for field in required_fields:
            if field not in spec:
                print(f"❌ Missing required field: {field}")
                return False
        
        print(f"✅ OpenAPI spec is valid")
        print(f"   - Version: {spec['openapi']}")
        print(f"   - API Version: {spec['info']['version']}")
        print(f"   - Endpoints: {len(spec['paths'])}")
        
        # List endpoints
        print(f"\n📡 Endpoints:")
        for path, methods in spec['paths'].items():
            for method in methods.keys():
                print(f"   {method.upper()} {path}")
        
        return True
    except json.JSONDecodeError as e:
        print(f"❌ Invalid JSON: {e}")
        return False
    except Exception as e:
        print(f"❌ Validation error: {e}")
        return False


def test_python_sdk_generation(spec_path: Path, output_dir: Path) -> bool:
    """Test Python SDK generation using openapi-python-client as alternative."""
    print(f"\n🐍 Testing Python SDK generation...")
    
    # Try using openapi-python-client (lighter alternative)
    try:
        result = subprocess.run(
            ["pip", "show", "openapi-python-client"],
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            print("   Installing openapi-python-client...")
            subprocess.run(
                ["pip", "install", "openapi-python-client"],
                check=True
            )
        
        print(f"   Generating Python SDK...")
        result = subprocess.run(
            [
                "openapi-python-client", "generate",
                "--path", str(spec_path),
                "--output-path", str(output_dir / "python"),
                "--package-name", "jotty_sdk"
            ],
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            print(f"✅ Python SDK generated successfully")
            print(f"   Location: {output_dir / 'python'}")
            return True
        else:
            print(f"⚠️  Generation had issues: {result.stderr}")
            return False
            
    except FileNotFoundError:
        print("   openapi-python-client not available, skipping Python SDK test")
        return False
    except Exception as e:
        print(f"   Error: {e}")
        return False


def test_typescript_sdk_manual(spec_path: Path) -> bool:
    """Test TypeScript SDK generation manually (simulate)."""
    print(f"\n📘 Testing TypeScript SDK structure...")
    
    # Read spec and generate a simple TypeScript client structure
    try:
        with open(spec_path) as f:
            spec = json.load(f)
        
        # Create a simple TypeScript client example
        ts_client = """// Auto-generated Jotty SDK
// This is a simplified example - full SDK would be generated by openapi-generator-cli

export interface ChatExecuteRequest {
  message?: string;
  messages?: ChatMessage[];
  history?: ChatMessage[];
  agentId?: string;
  provider?: string;
  model?: string;
}

export interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string | Array<{type: string; text: string}>;
  timestamp?: string;
}

export interface ChatExecuteResponse {
  success: boolean;
  final_output?: string;
  agent_id?: string;
  metadata?: Record<string, any>;
}

export class JottyClient {
  constructor(private baseUrl: string, private apiKey?: string) {}
  
  async chatExecute(request: ChatExecuteRequest): Promise<ChatExecuteResponse> {
    const response = await fetch(`${this.baseUrl}/api/chat/execute`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        ...(this.apiKey && { 'Authorization': `Bearer ${this.apiKey}` })
      },
      body: JSON.stringify(request)
    });
    return response.json();
  }
}
"""
        
        output_file = Path("sdk/generated/typescript-example.ts")
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(ts_client)
        
        print(f"✅ TypeScript client example created")
        print(f"   Location: {output_file}")
        print(f"   Note: Full SDK would be generated by openapi-generator-cli")
        return True
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return False


def create_test_use_case() -> bool:
    """Create a test use case to demonstrate SDK usage."""
    print(f"\n🧪 Creating test use cases...")
    
    # Python use case
    python_test = '''"""
Test use case for Jotty Python SDK
"""
from jotty_sdk import Configuration, ChatApi

def test_chat():
    """Test chat execution."""
    config = Configuration(
        host="http://localhost:8080",
        access_token="your-api-key"
    )
    
    chat_api = ChatApi(config)
    
    result = chat_api.chat_execute(
        body={
            "message": "Hello, how can you help?",
            "history": []
        }
    )
    
    print(f"Response: {result.final_output}")
    return result

if __name__ == "__main__":
    test_chat()
'''
    
    # TypeScript use case
    typescript_test = '''// Test use case for Jotty TypeScript SDK
import { JottyClient, ChatExecuteRequest } from './jotty-sdk';

async function testChat() {
    const client = new JottyClient('http://localhost:8080', 'your-api-key');
    
    const request: ChatExecuteRequest = {
        message: 'Hello, how can you help?',
        history: []
    };
    
    const result = await client.chatExecute(request);
    console.log(`Response: ${result.final_output}`);
    return result;
}

testChat().catch(console.error);
'''
    
    try:
        # Create test directories
        test_dir = Path("sdk/test_use_cases")
        test_dir.mkdir(parents=True, exist_ok=True)
        
        # Write Python test
        (test_dir / "test_python.py").write_text(python_test)
        
        # Write TypeScript test
        (test_dir / "test_typescript.ts").write_text(typescript_test)
        
        print(f"✅ Test use cases created")
        print(f"   - Python: {test_dir / 'test_python.py'}")
        print(f"   - TypeScript: {test_dir / 'test_typescript.ts'}")
        return True
        
    except Exception as e:
        print(f"❌ Error creating test cases: {e}")
        return False


def main():
    """Main test function."""
    print("="*60)
    print("🧪 Testing SDK Generation System")
    print("="*60)
    
    spec_path = Path("sdk/openapi.json")
    output_dir = Path("sdk/generated")
    
    # Step 1: Validate OpenAPI spec
    if not validate_openapi_spec(spec_path):
        print("\n❌ OpenAPI spec validation failed")
        sys.exit(1)
    
    # Step 2: Test Python SDK generation
    python_ok = test_python_sdk_generation(spec_path, output_dir)
    
    # Step 3: Test TypeScript SDK structure
    ts_ok = test_typescript_sdk_manual(spec_path)
    
    # Step 4: Create test use cases
    test_cases_ok = create_test_use_case()
    
    # Summary
    print("\n" + "="*60)
    print("📊 Test Summary")
    print("="*60)
    print(f"✅ OpenAPI Spec: Valid")
    print(f"{'✅' if python_ok else '⚠️ '} Python SDK: {'Generated' if python_ok else 'Skipped (install openapi-python-client)'}")
    print(f"{'✅' if ts_ok else '❌'} TypeScript SDK: {'Example created' if ts_ok else 'Failed'}")
    print(f"{'✅' if test_cases_ok else '❌'} Test Use Cases: {'Created' if test_cases_ok else 'Failed'}")
    
    print("\n💡 Next Steps:")
    print("   1. Install OpenAPI Generator: npm install -g @openapitools/openapi-generator-cli")
    print("   2. Generate all SDKs: python sdk/generate_sdks.py")
    print("   3. Test generated SDKs: cd sdk/generated/typescript-node && npm test")
    
    if python_ok or ts_ok:
        print("\n✅ SDK generation system is working!")
        return 0
    else:
        print("\n⚠️  Some tests skipped (OpenAPI Generator not installed)")
        print("   Install it to generate full SDKs: npm install -g @openapitools/openapi-generator-cli")
        return 0


if __name__ == "__main__":
    sys.exit(main())
